probabl-ai/skore

.commitlintrc.yml, .github/workflows/lint-pr-title.yml, CONTRIBUTING.md
- Add commitlint workflow to lint the PR title (not the individual PR commits)
- Make sentence-case the only allowed PR title format (first letter must be capitalized, like "Merge commit ..." or "Revert commit ...")
Closes #66
=> ci: Enforce conventional commit format in PR title

src/skore/item/sklearn_base_estimator_item.py, tests/unit/item/test_sklearn_base_estimator_item.py
Based on the skops tutorial: https://skops.readthedocs.io/en/stable/persistence.html#usage.
=> fix(SklearnBaseEstimatorItem): Temporarily disable skops's security feature

CONTRIBUTING.md
=> docs(contributing): Add minimal standard for contributing documentation

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/doc_improvement.yml, .github/ISSUE_TEMPLATE/feature_request.yml
=> chore: Create issue templates (#371)

.github/workflows/add-pr-assignee.yml, .github/workflows/backend.yml, .github/workflows/ci.yml, .github/workflows/frontend.yml, .github/workflows/lint.yml
- Remove reference of `Makefile` in workflow's instructions to build front-end
- Use matrix to test back-end on all versions of python `>=3.9` (only success on `3.12` is mandatory)
- Trigger CI tasks at job level instead of workflow level
- Use one and only entry-point to define if pipeline succeed `ci-all-green`
---
Example: https://github.com/probabl-ai/skore/actions/runs/11146672648
=> ci: Modularize CI pipeline and test Python >= 3.11

.github/workflows/release.yml, README.md, skore/pyproject.toml
To merge after https://github.com/probabl-ai/skore/pull/440 .
=> docs: Fix the skore description in PyPI

skore-ui/src/components/PlotlyWidget.vue
Animation frames were ignored in plotly construction. It's now fixed.
Closes #446
=> fix(UI): Add animation frames to plotly widgets

skore/src/skore/cli/create_project.py, skore/src/skore/cli/quickstart_command.py, skore/tests/integration/cli/test_create.py
Also, rename `ProjectAlreadyExists` to `ProjectAlreadyExistsError`.
Closes #484
=> refactor(cli-errors): Merge project validation exceptions into `InvalidProjectNameError`

.pre-commit-config.yaml
=> chore(pre-commit): Stop `nbstripout` from re-assigning cell IDs

skore-ui/src/assets/styles/_variables.css, skore-ui/src/components/FloatingTooltip.vue, skore-ui/src/main.ts, skore-ui/src/views/ComponentsView.vue
In prevision of #394 this PR adds a tooltip component.
Usage: 
```vue
<script setup>
import FloatingTooltip from "@/components/FloatingTooltip.vue";
</script>
<template>
<FloatingTooltip text="Tooltip on div">bottom tooltip</FloatingTooltip>
<FloatingTooltip text="Tooltip on div" placement="top">top tooltip</FloatingTooltip>
<FloatingTooltip text="Tooltip on div" placement="left">left tooltip</FloatingTooltip>
<FloatingTooltip text="Tooltip on div" placement="right">right tooltip</FloatingTooltip>
<FloatingTooltip placement="right">
html tooltip
<template #tooltipContent>
<span style="color: red">red content</span>
</template>
</FloatingTooltip>
</template>
```
UI preview:
https://github.com/user-attachments/assets/0b2a0d7c-654d-465f-a995-6266f45d60d5
=> feat(UI): Add a tooltip component

.pre-commit-config.yaml, skore/pyproject.toml, skore/src/skore/cli/launch_dashboard.py, skore/src/skore/persistence/abstract_storage.py, skore/src/skore/persistence/disk_cache_storage.py, skore/src/skore/persistence/in_memory_storage.py, skore/src/skore/ui/app.py
We can see in #541 that pre-commit doesn't execute ruff:
Now:
=> fix(ci): Fix ruff being skipped in CI by prefixing destinations with `skore/` after #440

skore-ui/src/ShareApp.vue, skore-ui/src/views/project/ProjectView.vue
Made a mistake during previous merge. This PR fixes dataframe hydration.
=> fix(UI): Datatable index name now points to the correct data attribute

skore/src/skore/cli/cli.py, skore/tests/unit/cli/test_cli.py
Previous behaviour was to try to launch project "project.skore" if no project name was given.
Closes #507
=> feat(cli): Remove default project argument in `launch` command

skore/src/skore/project.py, skore/tests/unit/test_project.py
Remove use of `singledispatchmethod`, which does not play well with keyword arguments. Instead, manually check the type of argument `key` and dispatch to `put_several` or to `put_one`, a new method which contains the logic formerly in `put`.
Closes #539
- **Add failing test**
- **Add Project.put_one**
- **Make `put` point either to `put_one` or to `put_several`**
=> fix(project): Make `project.put` work when called with keyword arguments

skore/src/skore/project.py, skore/tests/unit/test_project.py
This makes `put` raise upon error, instead of logging a warning.
When several key-value pairs are `put` at once, we `put` them in order, and stop and raise if we encounter an invalid pair.
Closes #540
=> feat(project): Remove `on_error` argument to `Project.put`

.gitignore, .pre-commit-config.yaml, docs/index.html, skore/pyproject.toml, sphinx/Makefile, sphinx/conf.py
Following the [official documentation](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-from-a-branch), i propose the current workflow to build the sphinx documentation:
1. (in the current iteration)
Use a dedicated `docs/` directory to store documentation artifacts that will be automatically rendered by GitHub on GitHub Pages.
Every time something changes in this directory on the `main` branch, the GitHub Pages will be refreshed.
So you can manually edit the site content on a PR, and push that PR on `main` to be applied.
Documentation can be managed independently of release.
2. (in the next iteration) 
Populate `docs/` by triggering `sphinx` in a GitHub action when something changes in the `skore/` …
=> feat: Add `/docs` used to deploy documentation to GitHub Pages

skore-ui/src/stores/project.ts, skore-ui/src/views/project/ProjectItemList.vue
This fixes two issues:
- Polling was not being done because the polling logic was commented out (see https://github.com/probabl-ai/skore/commit/0fa7a2e522449b06297857fe66f6aa7707484eea)
- Polling was not started again after adding an item to the view in some cases (see https://github.com/probabl-ai/skore/commit/83862a0e0595af53940c66fdb8cf29cfbd624a70)
It also removes a lingering `console.log`
Closes #581
=> fix(ui): Make polling work again

skore/src/skore/cross_validate.py
- Document *args and **kwargs more precisely and visibly.
- Fix erroneous return type annotation
=> docs(cross_validate): Make parameters description more precise

skore/src/skore/item/pandas_dataframe_item.py, skore/src/skore/ui/project_routes.py, skore/tests/unit/item/test_pandas_dataframe_item.py, skore/tests/unit/test_project.py
Pandas Dataframes including complex objects (e.g. numpy arrays) were stored as-is.
They are now serialized using JSON to make them environment-independent.
---
Two native methods are available to serialize dataframe with multi-index, while
keepping the index names:                                                      
1. Using table orientation with JSON serializer:                               
```python                                                                   
json = dataframe.to_json(orient="table")                                    
dataframe = pandas.read_json(json, orient="table", dtype=False)             
```                                                                         
This method fails when columns name is an integer.                          
2. Using …
=> fix(PandasDataFrameItem): Use JSON to serialize dataframe instead of pickle

skore/src/skore/item/cross_validation_item.py
The metrics that end in `_time` now show more readable time when hovered
on.
Screen record:
https://github.com/user-attachments/assets/6ffcd799-c37e-4f30-8113-4357e2ea552c
=> feat(cross-validation plot): Show datetimes using timedelta format

skore/src/skore/item/numpy_array_item.py, skore/src/skore/ui/project_routes.py, skore/tests/unit/item/test_numpy_array_item.py
Same problem as https://github.com/probabl-ai/skore/pull/621, but on `numpy.array`.
=> fix(NumpyArrayItem): Use JSON to serialize array instead of pickle

skore/src/skore/item/__init__.py, skore/src/skore/item/cross_validation_item.py, skore/src/skore/item/item.py, skore/src/skore/item/media_item.py, skore/src/skore/item/numpy_array_item.py, skore/src/skore/item/pandas_dataframe_item.py, skore/src/skore/item/pandas_series_item.py, skore/src/skore/item/primitive_item.py, skore/src/skore/item/sklearn_base_estimator_item.py, skore/tests/unit/item/test_cross_validation_item.py, skore/tests/unit/item/test_media_item.py, skore/tests/unit/item/test_numpy_array_item.py, skore/tests/unit/item/test_pandas_dataframe_item.py, skore/tests/unit/item/test_pandas_series_item.py, skore/tests/unit/item/test_primitive_item.py, skore/tests/unit/item/test_sklearn_base_estimator_item.py
Some `TypeError` exceptions are swallowed during item construction, but it should not:
Furthermore, during serialization, JSON can raise `TypeError`, that must not be catched.
=> fix(Item): Use specific exception in `item.factory` to not swallow unexpected exceptions in `object_to_item`

skore-ui/src/components/PlotlyWidget.vue, skore/src/skore/cross_validate.py, skore/src/skore/item/cross_validation_item.py, skore/src/skore/item/item_repository.py, skore/src/skore/ui/project_routes.py, skore/tests/integration/test_cross_validate.py, skore/tests/unit/item/test_cross_validation_item.py
This adds a new item type, `CrossValidationAggregationItem`, which allows to both record new cross-validation data (at key `cross_validation`), and update an aggregation plot (at key `cross_validation_aggregated`) when `skore.cross_validate` is called.
Co-authored-by: Auguste Baum <auguste@probabl.ai>
Closes #681
=> feat: Aggregate latest cross-validation and its history

skore-ui/src/components/TreeAccordionItem.vue
- pointer cursor is used when item is enabled
- grab cursor when label is clicked
- label now grows to use all available space (fixes #682)
- help cursor is used when item is disabled to indicate the scroll to item feature
https://github.com/user-attachments/assets/0aaea1b2-ba8c-400a-af95-7c2e2698af5f
Fixes #685
=> feat(UI): Item accordion now have dynamic cursor

examples/plot_03_cross_validate.py
Currently cross-validation aggregation works by manipulating the contents of the keys "cross_validation" and "cross_validation_aggregated", and we assume that the user is only working on one model so that it makes sense to compare different runs in a plot.
In example 3 of the docs we first perform cross-validation on a classification model, and then later on a regression model. Because of this, the aggregation process fails and the docs cannot be built.
This is a dirty, quick fix where we delete the contents of the keys "cross_validation" and "cross_validation_aggregated" before the regression example, to start fresh.
We are already planning more robust, automatic solutions to relax the "one-model" assumption: see
- https://github.com/probabl-ai/skore/issues/557
- …
=> fix(docs): Fix cross-validation example aggregation issues

skore-ui/src/components/ProjectViewCard.vue
Item history dropdown height is now max 40% of the viewport's height and a scrollbar may appear if needed.
=> feat(UI): Item history dropdown now as scrollbar

.github/actions/sphinx/build/action.yml, .github/actions/sphinx/deploy/action.yml, .github/workflows/sphinx.yml, .gitignore
Currently, a pull-request on `sphinx/` or `skore/` can break documentation building and be merged without notice.
---
=> ci: Ensure documentation can be built

.github/actions/sphinx/deploy/action.yml
Currently, the documentation bot push a new commit after building the documentation using a special token to sign commits.
It implies to re-run the CI for nothing with the latest changes https://github.com/probabl-ai/skore/pull/703.
---
The solution is to skip checks after commits of `github-actions[bot]`.
=> ci: Skip checks after commits of `github-actions[bot]`

skore-ui/src/views/project/ProjectView.vue
Change from element to item to be consistent with left panel naming and ease user understanding.
=> fix(ui): Update naming in new view from element to item

.github/workflows/lint-pr-title.yml
This fixes a bug where the workflow was skipped when a new commit was pushed to a PR with an offending title.
=> fix(ci): Make `lint-pr-title` run on PR `synchronize`

examples/plot_01_getting_started.py, examples/plot_02_overview_skore_ui.py, examples/plot_03_cross_validate.py
Proposes a couple of enhancement in the documentation.
- I reuse the pattern proposed by @adrinjalali. We discussed this morning IRL, and using the high-level API of the class seems better that the low-level functions.
- I move the import close to their first use because it is more intuitive when reading a notebook.
- Wrapping the line to have 88 characters in the description (so does it mean that linters are not run on those files?)
- I added links to the documentation instead of plain double back ticks when it makes sense.
=> docs: Improve example using the temporary folder and cleaning

examples/plot_01_getting_started.py, examples/plot_03_cross_validate.py, sphinx/_static/js/sg_plotly_resize.js, sphinx/conf.py
This should fix the issue observed on the documentation page.
It forces to resize the plotly figures once everything is loaded (and mainly the right sidebar).
Right now the bug is that the image is loaded and adapted before that the right sidebar is toggled (I think).
It feels like a hack but the rendering is better and our users should not see so much the difference since the figure are not shown as the first element of the page.
@rouk1 you might have a better understanding than me regarding all those JS stuff. So if this hack makes you think of the "right" way of fixing it, this could be cool.
=> docs(fix): Force plotly figure resizing after HTML/CSS layout loading

skore/src/skore/sklearn/cross_validate.py
=> docs(cross-validate): Name arguments to `cross_validate` explicitly

examples/plot_03_cross_validate.py, examples/plot_05_train_test_split.py, skore/src/skore/sklearn/train_test_split/train_test_split.py, skore/src/skore/sklearn/train_test_split/warning/high_class_imbalance_warning.py, sphinx/api.rst, sphinx/index.rst
=> fix(docs): Add an example for `skore.train_test_split`

skore/src/skore/sklearn/train_test_split/train_test_split.py, skore/src/skore/sklearn/train_test_split/warning/__init__.py, skore/src/skore/sklearn/train_test_split/warning/high_class_imbalance_too_few_examples_warning.py, skore/tests/unit/sklearn/train_test_split/test_train_test_split.py, skore/tests/unit/sklearn/train_test_split/warning/test_high_class_imbalance_too_few_examples_warning.py, skore/tests/unit/sklearn/train_test_split/warning/test_high_class_imbalance_warning.py
- Export train_test_split warnings through `train_test_split.warning` module
- refactor tests to mirror src
- Add new warning
Would welcome suggestions for a shorter name ^^' 
Addresses #684
=> feat: Add `HighClassImbalanceTooFewExamples` warning to `train_test_split`

skore/src/skore/sklearn/train_test_split/train_test_split.py, skore/tests/unit/sklearn/train_test_split/test_train_test_split.py
This fixes an issue where a warning was raised when X and y were passed positionally, but not when they were passed by keyword.
=> fix(train_test_split): Make behaviour the same when passing `y` by keyword

.github/workflows/skore.yml
As tests should run on a default encoding.
=> chore(CI): Remove PYTHONUTF8 from the CI 

sphinx/install.rst
=> fix(docs): Remove UTF8 warning

skore-ui/src/stores/project.ts
In a case insensitive fashion.
Note that the "self" items stays in top position if it exists.
=> feat(UI): Accordion's item are now alpahabetically sorted

skore/hatch/metadata.py, skore/pyproject.toml, skore/src/skore/sklearn/train_test_split/train_test_split.py, skore/src/skore/sklearn/train_test_split/warning/__init__.py, skore/src/skore/sklearn/train_test_split/warning/high_class_imbalance_too_few_examples_warning.py, skore/src/skore/sklearn/train_test_split/warning/high_class_imbalance_warning.py, skore/src/skore/sklearn/train_test_split/warning/random_state_unset_warning.py, skore/src/skore/sklearn/train_test_split/warning/shuffle_true_warning.py, skore/src/skore/sklearn/train_test_split/warning/stratify_is_set_warning.py, skore/src/skore/sklearn/train_test_split/warning/time_based_column_warning.py, skore/src/skore/sklearn/train_test_split/warning/train_test_split_warning.py, skore/tests/unit/sklearn/train_test_split/test_train_test_split.py, skore/tests/unit/sklearn/train_test_split/warning/test_high_class_imbalance_too_few_examples_warning.py, skore/tests/unit/sklearn/train_test_split/warning/test_high_class_imbalance_warning.py, skore/tests/unit/sklearn/train_test_split/warning/test_stratify_warning.py, skore/tests/unit/sklearn/train_test_split/warning/test_time_based_column_warning.py
This implementation has been tested for pandas and polars dataframes, and checks whether the dtype of any column matches the string "date". Thus, we assume that the dtypes are accurate (no clever string parsing yet).
Because the new warning's message is dynamic (it includes the name or index of the first offending column), I took the opportunity to simplify the `TrainTestSplitWarning` interface: now, only the `check` method is expected, and it returns either `None` or a warning message string.
Addresses #684
=> feat(train_test_split): Add "time-based column" warning

docs/design/0000-adr-template.md, docs/design/0001-postpone-narwhals.md, docs/design/README.md, skore/pyproject.toml, skore/src/skore/item/__init__.py, skore/src/skore/item/item_repository.py, skore/src/skore/item/polars_dataframe_item.py, skore/src/skore/item/polars_series_item.py, skore/src/skore/project/project.py, skore/src/skore/ui/project_routes.py, skore/tests/unit/item/test_pandas_dataframe_item.py, skore/tests/unit/item/test_pandas_series_item.py, skore/tests/unit/item/test_polars_dataframe_item.py, skore/tests/unit/item/test_polars_series_item.py, skore/tests/unit/test_project.py
- Copy-pasted all the pre-existing code concerning pandas into its polars equivalent
- Adapted as needed
- For instance, polars dataframes don't have an Index, so I deleted all mentions of it in the polars version
- Unlike pandas, polars raises a `ComputeError` when serializing a DataFrame that contains a complex object, e.g. a numpy array.
- Added the Polars Items to the UI routes
- Used `to_pandas` which requires `pyarrow`
It was [suggested](https://github.com/probabl-ai/skore/pull/792#issuecomment-2498980110) that we might use narwhals for the implementation. For this PR I went without it, for these reasons:
- I wanted to avoid adding a dependency (unfortunately, I still ended up adding pyarrow for the specific case of transferring data from a Project to skore-ui).
- I have never used …
=> feat(project): Add first-class support for polars dataframes

skore/src/skore/cli/cli.py, skore/src/skore/cli/quickstart_command.py, skore/tests/unit/cli/test_cli.py, skore/tests/unit/cli/test_quickstart.py
The PR contains a fair amount of code duplication, presumably because I'm missing something about `argparse`.
Closes #725
TODO:
=> feat(cli): Make `create` and `launch` parameters usable with `quickstart`

.github/workflows/release.yml
We don't need to fill the `deployment` section of GH, as long as we do only releases.
=> ci: Remove reference of the release environment

skore/src/skore/ui/project_routes.py, skore/tests/integration/ui/test_ui.py
Fixes #853.
Bonus: projects_routes.py coverage is now higher.
=> fix(API): Do not use base64 for text types

skore/src/skore/ui/project_routes.py, skore/tests/integration/ui/test_ui.py
Author: Thomas S <thomas@probabl.ai>
Author: Matt J <matthieu@probabl.ai>
---
Part of #767 .
=> feat: Add a new backend API for activity feed

skore/src/skore/item/cross_validation_item.py
Previously the tooltip was only shown when hovering on the extreme right or left of the plot.
Addresses #686
https://github.com/user-attachments/assets/c75ffeff-dc85-4526-bc6b-93d8afa119fe
=> fix(cross-validation plot): Fix hover on horizontal lines

skore/src/skore/sklearn/train_test_split/warning/high_class_imbalance_warning.py
```
import skore
my_project = skore.create("my_project")
File [...]/skore/sklearn/train_test_split/warning/high_class_imbalance_warning.py:10
6 from __future__ import annotations
8 from typing import TYPE_CHECKING, Any, Optional, Union
---> 10 import pandas
12 from skore.sklearn.train_test_split.warning.train_test_split_warning import (
13     TrainTestSplitWarning,
14 )
16 if TYPE_CHECKING:
ModuleNotFoundError: No module named 'pandas'
```
=> fix: Remove undeclared dependency `pandas` from warning class

skore/pyproject.toml
It seems that we are not compatible with `scikit-learn ==1.6`.
```
Unexpected failing examples (2):
../examples/01_track/plot_01_overview_skore_project.py failed leaving traceback:
Traceback (most recent call last):
File "/home/runner/work/skore/skore/examples/01_track/plot_01_overview_skore_project.py", line 348, in <module>
my_project.put("my_model", my_model)
File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/skore/project/project.py", line 130, in put
self.__put_one(key, value)
File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/skore/project/project.py", line 147, in __put_one
item = object_to_item(value)
^^^^^^^^^^^^^^^^^^^^^
File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/skore/item/__init__.py", line 45, in …
```
=> ci: Use `scikit-learn <1.6` temporarily

skore/src/skore/item/cross_validation_item.py, skore/src/skore/sklearn/train_test_split/train_test_split.py, skore/tests/unit/item/test_cross_validation_item.py
Part of https://github.com/probabl-ai/skore/issues/886.
As a user will never instanciate a `CrossValidationItem` himself, make sure `CrossValidationItem` creation comes from `CrossValidationReporter`, so the `object_to_item` fallback is not triggered by a simple dictionary (and remains meaningful).
- In `CrossValidationItem`, test class with `isinstance` by fixing circular imports
- In `CrossValidationItem`, remove the possibility to use factory other than with a `CrossValidationReporter`.
=> feat: Make sure CrossValidationItem creation comes from CrossValidationReporter

skore/pyproject.toml
`scikit-learn` is used in `/sklearn/cross_validation/` and `/sklearn/train_test_split/`.
=> chore(deps): Use scikit-learn <1.7 in skore dependencies

skore/src/skore/item/cross_validation_aggregation_item.py, skore/tests/integration/sklearn/test_cross_validate.py
Closes #908
Note that this makes it easier than before to compare cross-validation runs that have nothing to do with one another.
=> fix(cross-validation aggregation): Allow aggregation of runs with different metrics

skore/src/skore/item/media_item.py
Matplotlib plots now use "tight" bounding box.
=> fix: Use tight bounding box for matplotlib item

skore/hatch/metadata.py
closes #743 
It is a fix to include the LICENSE file into the `tar.gz`.
=> fix: Include the LICENSE file in tar.gz source

skore/src/skore/ui/project_routes.py, skore/tests/integration/ui/test_ui.py
Fixes a bug introduced in https://github.com/probabl-ai/skore/pull/964/ where the plot was outputted to a non-serializable object
=> fix: Correct serialization of CrossValidationItem for UI

.gitignore
```
[...]
skore-0.0.0+unknown/.gitignore
skore-0.0.0+unknown/LICENSE
skore-0.0.0+unknown/pyproject.toml
skore-0.0.0+unknown/PKG-INFO
[...]
skore-0.0.0+unknown.dist-info/METADATA
skore-0.0.0+unknown.dist-info/WHEEL
skore-0.0.0+unknown.dist-info/entry_points.txt
skore-0.0.0+unknown.dist-info/licenses/LICENSE
skore-0.0.0+unknown.dist-info/RECORD
```
=> fix: Exclude `skore/LICENSE` from tracked files after #948

.github/workflows/skore.yml, skore/pyproject.toml
`pytest-xdist` allows to run the test in parallel.
As the test suite will grow, it might be handy for little cost in terms of maintenance.
=> chore: Allow to run tests in parallel using pytest-xdist

sphinx/api.rst
Adds sections in the navigation bar as requested in https://github.com/probabl-ai/skore/issues/836.  
in we want toggle menus instead, we can add `"show_nav_level": 0,` in html_theme_options dict.
=> docs: Group the left menu of APIs

skore/src/skore/sklearn/cross_validation/cross_validation_helpers.py, skore/tests/integration/sklearn/test_cross_validate.py
Partially addressed #1006 
closes #1010 
This PR partially addressed one of the issue triggered in #1006
The `make_scorer` for the `log_loss` and `brier_score` do not get the right type of predictions (it should be the output of `predict_proba`).
=> fix: Pass the right response_method to the underlying make_scorer

.github/workflows/skore-ui.yml, .github/workflows/skore.yml
Temporarily deactivate coverage comments on PRs from fork, which don't have enough permissions.
=> ci: Temporarily deactivate coverage comments on PRs from fork

CONTRIBUTING.rst
=> docs: Fix `CONTRIBUTING.md` to create project

skore/src/skore/cli/launch_dashboard.py, skore/src/skore/cli/quickstart_command.py, skore/tests/unit/cli/test_quickstart.py
=> fix: Fix quickstart instruction in CLI

skore/src/skore/utils/_show_versions.py, skore/tests/unit/utils/test_show_versions.py
closes #987 
Make `skore.show_vertsions()` robust to version specifiers in the requirements defined in `pyproject.toml`.
=> fix: Make skore.show_versions() robust to version specifiers in requirements

.gitignore, README.md, skore/pyproject.toml, sphinx/index.rst
=> chore: Update tagline

skore/src/skore/sklearn/cross_validation/cross_validation_helpers.py, skore/src/skore/sklearn/cross_validation/cross_validation_reporter.py
Addressing the issue specified in https://github.com/probabl-ai/skore/pull/916#issuecomment-2578540475
Because in scikit-learn 1.4, `check_estimator` does not accept `estimator=None`. Luckily, we have the available estimator so we can provide it to `_add_scorers` as a workaround and since `scoring is not None` we don't have any change of behaviour anyway.
=> fix: Make _add_scorers compatible with sklearn 1.4

skore/src/skore/sklearn/cross_validation/cross_validation_helpers.py, skore/tests/unit/sklearn/test_cross_validate.py
closes #1050 
As specified, do not try to compute Brier score with an estimator that does not provide probability estimate (i.e. does not have a `predict_proba` method).
Added a non-regression test as well.
=> fix: Do not compute Brier score when predict_proba is not available

skore/src/skore/item/cross_validation_item.py, skore/tests/unit/item/test_cross_validation_item.py
closes #1061 
We are more flexible using a regular expression to check the score names. In addition, we take care to test first the `neg_` part that would mean that negative score are therefore "higher is greater" convention.
=> fix: Use a more flexible approach to check favorability of metrics

.github/workflows/skore.yml, skore/src/skore/sklearn/cross_validation/cross_validation_helpers.py, skore/src/skore/sklearn/cross_validation/cross_validation_reporter.py
Refactor `skore.yml` workflow:
- launch tests with the 3 latest major versions of `scikit-learn` on `os: "ubuntu-latest"` and `python: "3.12"`,
- speed-up tests by installing dependencies in `venv`and caching it.
And make `_add_scorers` compatible with `sklearn ==1.4`.
=> ci: Test with the 3 latest major versions of `scikit-learn`

skore-ui/src/assets/styles/_variables.css, skore-ui/src/assets/styles/main.css, skore-ui/src/components/DropdownButtonItem.vue, skore-ui/src/components/EditableListItem.vue, skore-ui/src/components/ProjectViewCard.vue, skore-ui/src/components/TreeAccordionItem.vue, skore-ui/src/views/activity/ActivityFeedView.vue, skore-ui/src/views/project/ProjectView.vue, skore-ui/src/views/project/ProjectViewNavigator.vue
Removed pure blue background on editable text (view selector)
And various color fixes on dark/light switch.
Fixes #890 & #1011.
=> fix(UI): Use default background color for selected text and misc fixes

skore/src/skore/sklearn/_estimator/report.py, skore/tests/unit/sklearn/test_estimator.py
Closes #1081
When initializing the `EstimatorReport`, we now `deepcopy` the input estimator unless it is `cloned`.
This way, if the user re-fits their estimator after giving it as input to `EstimatorReport`, this will have no impact on the report itself.
If `deepcopy` doesn't succeed, we keep the previous behaviour and issue a warning about the potential side-effects.
=> fix(EstimatorReport): Make a deep copy of fitted estimator in constructor to avoid side-effect

skore/src/skore/sklearn/train_test_split/train_test_split.py, skore/tests/unit/sklearn/train_test_split/test_train_test_split.py
closes #1060 
It is the alternative to #1060 using `rich`. I added a test to check that we can filter the warning since we are not using the usual `warnings` module.
In the future, we could factor out the code in a utils to be sure that we can also transform the warnings into error.
=> feat: Use rich Panel for showing warning in train_test_split

README.md, examples/getting_started/plot_quick_start.py
Fix #1018 
In quick start example, do not use SVC on the Iris dataset, but rather logistic regression
=> docs: Use logistic regression instead of SVC on the Iris dataset

sphinx/api.rst, sphinx/conf.py
=> docs(api): Join sidebar sections

examples/getting_started/plot_skore_product_tour.py, examples/getting_started/plot_working_with_projects.py, sphinx/conf.py
I followed the [sphinx-gallery docs](https://sphinx-gallery.github.io/stable/advanced.html#resetting-before-each-example).
I tried to place `reset_mpl` in a different module in the hopes of removing the warning about sphinx not being able to cache `sphinx_gallery_conf`, but I couldn't manage to make the import work. I noticed sklearn declares a function in `conf.py` as well so I don't think it's too big a deal.
Closes #675
=> docs: Reset figure DPI before each example

skore/src/skore/sklearn/_estimator/metrics_accessor.py, skore/src/skore/sklearn/_estimator/report.py, skore/src/skore/sklearn/_plot/roc_curve.py
Fixing the type of `pos_label` in the different docstrings.
Here, it is the most consistent types that are accepted.
=> docs: Fix the type of  parameter

skore/src/skore/sklearn/_base.py, skore/src/skore/sklearn/_base.pyi, skore/src/skore/sklearn/_estimator/metrics_accessor.py, skore/src/skore/sklearn/_estimator/metrics_accessor.pyi, skore/src/skore/sklearn/_estimator/report.py, skore/src/skore/sklearn/_estimator/report.pyi, skore/tests/unit/sklearn/test_base.py
It is a refactor to ease the review in #1091.
It is only moving the file from `sklearn/_estimator/base.py` to `sklearn/_base.py` since some base class will be in common between the `EstimatorReport` and `CrossValidationReport`.
In addition, I factor out an additional base class link to the help of the `*Report` class and the `_get_cached_response_values` that will also be used in the `CrossValidationReport`.
So in short, there is no new code here.
=> chore: Move base.py outside from _estimator module

docs/design/0003-use-union-rather-than-pipe.md, skore/src/skore/externals/_sklearn_compat.py, skore/src/skore/item/cross_validation_item.py, skore/src/skore/item/item.py, skore/src/skore/item/item_repository.py, skore/src/skore/item/media_item.py, skore/src/skore/item/numpy_array_item.py, skore/src/skore/item/pandas_dataframe_item.py, skore/src/skore/item/pandas_series_item.py, skore/src/skore/item/polars_dataframe_item.py, skore/src/skore/item/polars_series_item.py, skore/src/skore/item/primitive_item.py, skore/src/skore/item/sklearn_base_estimator_item.py, skore/src/skore/project/project.py, skore/tests/unit/item/test_item_repository.py, skore/tests/unit/item/test_media_item.py, skore/tests/unit/item/test_numpy_array_item.py, skore/tests/unit/item/test_pandas_dataframe_item.py, skore/tests/unit/item/test_pandas_series_item.py, skore/tests/unit/item/test_polars_dataframe_item.py, skore/tests/unit/item/test_polars_series_item.py, skore/tests/unit/item/test_primitive_item.py, skore/tests/unit/item/test_sklearn_base_estimator_item.py, skore/tests/unit/project/test_notes.py
New methods have been added to `Project`:
```python
project.set_note(key, message, version=-1)
project.get_note(key, message, version=-1)
project.delete_note(key, message, version=-1)
```
To this end,
- `Item` now has an additional attribute, `note`, which is a `str | None`
- `ItemRepository` has similar methods
The note related methods fail with a KeyError when the key-version combination does not exist, but:
- `get_note` returns `None` if the note is `None` (no error)
- `delete_note` never errors if the key-version combination exists (even if the note is already `None`, it will be set to `None` again)
`set_note` fails with a TypeError if `key` or `message` is not a string.
Addresses part of #1041
=> feat: Implement note-related methods

skore/src/skore/project/project.py, skore/tests/unit/project/test_notes.py
Implementation notes:
At first I used `set_note` directly, to delegate the type-checking process, but that meant touching the storage 2 times instead of 1.
=> feat(project.put): Add `note` argument

skore/src/skore/sklearn/_estimator/report.py
Fixing some outdated information from previous iteration.
`unfitted_estimator` and `fitted_estimator` are not available anymore because we use the constructor directly.
=> fix: Fix the error message regarding immutable attribute

skore/src/skore/sklearn/_estimator/report.py
I might slight refactor such that we concatenate list instead of tuple and associate the `data_source` and `X` to make more straightforward.
There is no change in the tests because the outcome is equivalent.
=> chore: More readable version to create variable to iterate on in cache_predictions

.github/workflows/sphinx.yml
To fix the documentation access latency on S3, @jerome-probabl has added a CDN with a 24-hour policy.
This PR intends to purge the CDN cache after each documentation deployment.
=> ci: Purge documentation CDN cache

skore/src/skore/sklearn/_base.py, skore/src/skore/sklearn/_estimator/metrics_accessor.py, skore/src/skore/sklearn/_estimator/report.py, skore/tests/unit/sklearn/test_estimator.py
closes #1103 
As suggested in #1103, let's differentiate the output of `help` with the output of the `repr`. Let's have a concise output for `repr` to show where to get the information.
=> chore: Differentiate __repr__ and help for report and accessors

examples/getting_started/plot_skore_product_tour.py, examples/getting_started/plot_tracking_items.py
Fix #1124 
Just a couple of minor changes in variables naming, etc
=> docs: Minor changes in the doc (tracking items example)

skore/src/skore/sklearn/_estimator/metrics_accessor.py, skore/tests/unit/sklearn/test_estimator.py
This PR exposes private metrics to expose the `data_source_hash` such we can compute it once and pass it around whenever possible. It is particularly interested because the hash might be expensive to compute on huge dataset.
=> feat: Private API to expose `data_source_hash` when computing metric

examples/model_evaluation/plot_estimator_report.py, skore/src/skore/sklearn/_estimator/metrics_accessor.py, skore/tests/unit/sklearn/test_estimator.py
This PR makes sure that we can pass `pos_label` either as a parameter to a scikit-learn scorer or as a parameter of the skore function. If both are provided, we just make sure that the values of both input are coherent. Otherwise, we raise an informative error.
=> fix: Support passing pos_label as scorer param or as method param

skore/src/skore/item/item_repository.py, skore/tests/conftest.py, skore/tests/unit/project/test_notes.py
The storage API was not used correctly which resulted in not saving the notes properly; this affected `set_note` and `delete_note`.
The issue was not detected in unit tests because they relied on an in-memory project, not a "real" on-disk project.
=> fix(notes api): Make ItemRepository save notes properly

skore/src/skore/sklearn/_base.py, skore/src/skore/sklearn/_base.pyi, skore/src/skore/sklearn/_estimator/metrics_accessor.py, skore/src/skore/sklearn/_estimator/report.py, skore/src/skore/sklearn/_estimator/utils.py, skore/tests/unit/sklearn/test_base.py, skore/tests/unit/sklearn/test_estimator.py
closes #1118 
As proposed in #1118. Add `_` at the end of the variables that we alter in the constructor to follow the scikit-learn convention.
=> refactor: Prepend with  name of variable that we modify

skore/src/skore/sklearn/find_ml_task.py, skore/tests/unit/sklearn/test_utils.py
Closes #1080
Adds more logic in the case where `y` is detected as multiclass classification: we now additionally check whether `y` is a vector or sequential values that contains 0 (if so, we output "multiclass-classification", otherwise "regression"). This heuristic is suggested by @koaning.
=> feat(_find_ml_task): Refine ML task detection logic

skore/src/skore/sklearn/find_ml_task.py, skore/tests/unit/sklearn/test_utils.py
=> fix(_find_ml_task): Deal with case where estimator is unfitted and `y` is None

skore/src/skore/utils/_patch.py
closes #1132
The current patch was clean but not optimal: it was patching a public class. However, it involves calling `display()` once to create the ipywidget and then once for injection the CSS rule. I assume that the timing between the two displays call was actually the blinking observe.
This PR patch the function creating the HTML code block for the widget and concatenate the CSS rule and thus involve a single call to display and remove the blinking.
=> fix: Fix rendering in ipywidget by injecting CSS rule asap

skore/src/skore/ui/app.py, skore/src/skore/ui/templates/404.html
Closes #1003 
When running skore from source, it occurs that some contributors where puzzled by the nonexistence of the UI. This PR introduces a 404 page if the UI as not been built.
=> feat: 404 page when skore-UI as not been built

.github/workflows/backend.yml
Looking a bit more, it seems not only the `coverage` job is problematic. So since we are using `-n auto`, it means that we potentially allocate too many cores (logical + physical) and potentially some test allocate even more parallel jobs (usually I tried some jobs with `n_jobs=2`). So we could have a problem of over-subscription and not problem of deadlocks.
Let see if we have the same issue by limiting the number of worker.
=> ci: Fix timeout by upgrading scikit-learn to latest bugfix

skore/src/skore/sklearn/_plot/utils.py, skore/tests/unit/sklearn/plot/test_common.py
closes #1150 
This changes proposed to have a conventional `repr` for display to avoid to interfere too much with the output and have a richer `str`.
=> fix: Have shorter repr for display and longer str

skore/src/skore/sklearn/_estimator/report.py, skore/tests/unit/sklearn/test_estimator.py
While coding an example, I realized that by default we can trigger the `pos_label=None` with binary classification and thus it should be cached as well.
I added amended the according test as well.
=> fix: Cache the pos_label=None when calling cache_predictions

sphinx/conf.py
Fix part of #1019
✅ We can set an explicit order for the subsections (the categories of examples):
```python
subsections_order = [
"../examples/getting_started",
"../examples/model_evaluation",
]
sphinx_gallery_conf = {
"subsection_order": ExplicitOrder(subsections_order),  # sorting gallery subsections,
}
```
❌ Inside a subsection, we can sort the examples by example title:
```python
sphinx_gallery_conf = {
"within_subsection_order": "ExampleTitleSortKey",
}
```
but I can't set an explicit order myself for the examples in `getting_started` and in `model_evaluation`.
This will be for another PR.
=> docs: Order the example sections manually

.github/CODEOWNERS
Auguste has created a dedicated professional GH account.
This PR switches its account from personal to professional in the CODEOWNERS file.
=> ci: Change the username of Auguste in CODEOWNERS file

skore-ui/src/views/project/ItemNote.vue
When saving a note using <kbd>shift</kbd> + <kbd>enter</kbd> or <kbd>meta</kbd> + <kbd>enter</kbd> all line feed at the end will be removed (in frontend aswell as in backend).
=> fix(UI): Trim all line feed from end of note

.github/actions/sphinx/build/action.yml, .github/workflows/pr-serve-documentation-preview.yml, .github/workflows/sphinx.yml, sphinx/Makefile, sphinx/conf.py
Use GH environment variables to fill the documentation domain.
In order to be resilient to any domain name changes, centralize the domain name in GH settings.
=> ci: Use GH environment variables to fill the documentation domain

examples/getting_started/plot_tracking_items.py, skore/src/skore/project/project.py, skore/tests/unit/project/test_project.py
Following #1052 , change the API to be compliant with `set_note` and @MarieS-WiMLDS comments.
=> feat: Replace the latest parameter by version in `Project.get`

skore/src/skore/sklearn/_cross_validation/report.py, skore/src/skore/sklearn/_estimator/report.py, skore/src/skore/utils/_progress_bar.py, skore/tests/unit/sklearn/test_cross_validation.py, skore/tests/unit/sklearn/test_estimator.py, skore/tests/unit/utils/test_progress_bar.py
This PR makes sure that the `EstimatorReport` and `CrossValidationReport` are pickable object.
Right now, because we kept the step of the `Progress` from rich that has a lock, the object are not pickable. I reset the `_parent_progress` and `_progress_info` to `None` in the finally of the decorator.
An alternative is to change the `set_state` but here I think that we can just applied this clean-up instead.
=> fix: Make reports pickable out-of-the-box

sphinx/_static/images/2024_12_12_skore_activity_feed.png, sphinx/_static/images/2024_12_12_skore_cross_val.png, sphinx/_static/images/2024_12_12_skore_cross_val_clf.png, sphinx/_static/images/2024_12_12_skore_demo_comp.gif, sphinx/_static/images/2024_12_12_skore_tracking_comp.gif
=> docs: Remove images/gif that are not used anymore, in any documentation version

.github/workflows/sphinx.yml
To avoid endless pipeline, add a timeout when building sphinx documentation.
=> ci: Add timeout to sphinx building pipeline

.github/workflows/sphinx.yml
Temporarily fix the sphinx pipeline by downloading the `skrub` cache, which i put directly on our bucket under a random directory.
`skrub` using the user home to cache data, i set the `home` envar.
---
Content of the archive:
```
skrub_data/
skrub_data/openml/
skrub_data/openml/employee_salaries.csv
skrub_data/openml/open_payments.csv
skrub_data/openml/openml/
skrub_data/openml/openml/openml.org/
skrub_data/openml/openml/openml.org/api/
skrub_data/openml/openml/openml.org/api/v1/
skrub_data/openml/openml/openml.org/api/v1/json/
skrub_data/openml/openml/openml.org/api/v1/json/data/
skrub_data/openml/openml/openml.org/api/v1/json/data/42125.gz
skrub_data/openml/openml/openml.org/api/v1/json/data/features/
skrub_data/openml/openml/openml.org/api/v1/json/data/features/42125.gz …
```
=> ci: Temporarily fix the sphinx pipeline by downloading our own skrub cache

README.md, examples/getting_started/plot_quick_start.py, examples/getting_started/plot_skore_getting_started.py, examples/getting_started/plot_skore_product_tour.py, examples/model_evaluation/plot_estimator_report.py
=> docs: Update documentation now that we have the EstimatorReport to showcase and no UI

sphinx/conf.py
=> docs: Stop showing typehints in API docs

sphinx/Makefile
Fix sphinx building pipeline on forks where `vars.DOCUMENTATION_DOMAIN` is not provisioned.
=> ci: Fix sphinx building pipeline

README.md, examples/getting_started/plot_quick_start.py
specify `create=True` on `open`
=> docs: Minor changes in the examples (about `open`)

skore-ui/src/components/DraggableList.vue
As `DraggableList` now use another strategy to move item and presents the drag feedback, it occurs that raster of all items is not needed anymore.
Indeed this leads to a nice optimisation in responsiveness especially when using large table reports.
Closes #1177.
=> fix(UI): Remove rasterizing of items in draggable lists

skore/src/skore/persistence/item/altair_chart_item.py, skore/src/skore/persistence/item/cross_validation_reporter_item.py, skore/src/skore/persistence/item/matplotlib_figure_item.py, skore/src/skore/persistence/item/pickle_item.py, skore/src/skore/persistence/item/pillow_image_item.py, skore/src/skore/persistence/item/plotly_figure_item.py, skore/src/skore/persistence/item/sklearn_base_estimator_item.py, skore/src/skore/utils/__init__.py, skore/tests/unit/item/test_altair_chart_item.py, skore/tests/unit/item/test_cross_validation_reporter_item.py, skore/tests/unit/item/test_matplotlib_figure_item.py, skore/tests/unit/item/test_pickle_item.py, skore/tests/unit/item/test_pillow_image_item.py, skore/tests/unit/item/test_plotly_figure_item.py, skore/tests/unit/item/test_sklearn_base_estimator_item.py
This PR intends to persist b64 string inplace of bytes.
The latest isn't JSONable, so items can't be easily persisted without a pickle backend.
=> fix: Persist base64 string instead of bytes to ensure items are JSONable

skore/src/skore/persistence/item/numpy_array_item.py, skore/tests/unit/item/test_numpy_array_item.py
Only for storage for now; `array.tolist()` is still used for sending data to the UI.
The `allow_pickle=False` setting is used to keep the same behaviour for arrays.
Closes https://github.com/probabl-ai/skore/issues/1159
=> feat(NumpyArrayItem): Use `numpy.save` instead of `array.tolist()`

skore/src/skore/project/project.py
Follow-up for #1194 
Related to a question from @rouk1 https://github.com/probabl-ai/skore/pull/1194#issuecomment-2622256091
I think that we should improve the error message, whatever the default value is.
=> chore: Improve error message when if_exist='raise'

skore-ui/src/components/DataFrameWidget.vue, skore-ui/src/components/TextInput.vue
Especially in  in dark mode.
It now looks like:
=> fix(UI): Dataframe widget does not use consistent text color

skore/src/skore/ui/app.py
Follow-up for https://github.com/probabl-ai/skore/pull/1194 and the comment https://github.com/probabl-ai/skore/pull/1194#issuecomment-2622458300 of @rouk1.
=> revert: Instantiate the default project when `create_app` is invoked by uvicorn from CLI

.github/workflows/backend.yml, .github/workflows/frontend.yml
Following https://github.com/probabl-ai/skore/pull/1238.
Currently, any change on `skore/hatch/`, `skore/ci/` or `skore/*.*` doesn't trigger the backend worflow.
This can lead to undetected bug.
=> ci: Run backend workflow after any change on `skore/`

examples/getting_started/plot_skore_getting_started.py
=> docs: Minor changes

skore-ui/package.json
See dependabot alert in the security tab of the repo.
=> chore: Upgrade vitest to patch CVE-2025-24964

skore/src/skore/sklearn/_cross_validation/report.py, skore/tests/unit/sklearn/test_cross_validation.py
Exceptions in `CrossValidationReport._fit_estimator_reports` no longer cause the previously computed estimators to be thrown away.
Here is a manual test using the following snippet: 
```python
import time
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from skore import CrossValidationReport
class SlowEstimator(LogisticRegression):
def __init__(self):
super().__init__()
def fit(self, X, y):
time.sleep(0.5)
super().fit(X, y)
return self
X, y = make_classification(random_state=42)
estimator = SlowEstimator()
#
#
report = CrossValidationReport(estimator, X=X, y=y, cv_splitter=5)
```
Closes #1024
=> feat(CrossValidationReporter): Catch exceptions during cross-validation

README.md, examples/getting_started/plot_quick_start.py, examples/getting_started/plot_skore_getting_started.py, examples/model_evaluation/plot_estimator_report.py, examples/technical_details/plot_cache_mechanism.py, examples/use_cases/plot_employee_salaries.py, skore/src/skore/sklearn/_cross_validation/__init__.py, skore/src/skore/sklearn/_cross_validation/metrics_accessor.py, skore/src/skore/sklearn/_estimator/__init__.py, skore/src/skore/sklearn/_estimator/metrics_accessor.py, skore/src/skore/sklearn/_plot/precision_recall_curve.py, skore/src/skore/sklearn/_plot/prediction_error.py, skore/src/skore/sklearn/_plot/roc_curve.py, skore/tests/unit/sklearn/plot/test_common.py, skore/tests/unit/sklearn/plot/test_precision_recall_curve.py, skore/tests/unit/sklearn/plot/test_prediction_error.py, skore/tests/unit/sklearn/plot/test_roc_curve.py, skore/tests/unit/sklearn/test_cross_validation.py, skore/tests/unit/sklearn/test_estimator.py, sphinx/api.rst
This PR removes the `.metrics.plot` sub-accessor to make it available at the `.metrics` level.
It allows to have a consistent access with dataframe, e.g.:
```python
report.metrics.report_metrics().plot()
report.metrics.roc().plot()
```
=> fix(api): Remove the plot sub-accessor

examples/getting_started/plot_skore_getting_started.py, examples/model_evaluation/plot_estimator_report.py, examples/use_cases/plot_employee_salaries.py, skore/src/skore/sklearn/_cross_validation/metrics_accessor.py, skore/src/skore/sklearn/_estimator/metrics_accessor.py, skore/src/skore/sklearn/_plot/precision_recall_curve.py, skore/src/skore/sklearn/_plot/prediction_error.py, skore/src/skore/sklearn/_plot/roc_curve.py, skore/src/skore/sklearn/_plot/utils.py, skore/tests/unit/sklearn/plot/test_precision_recall_curve.py, skore/tests/unit/sklearn/plot/test_prediction_error.py, skore/tests/unit/sklearn/plot/test_roc_curve.py
closes #1298 
This PR makes sure that the display factory does not call `.plot()` directly.
It allows:
- to pass plotting parameters to be passed only to `display.plot()`
- to have a consistent api as for pandas object like dataframe:
```python
report.metrics.report_metrics().plot(kind="barh")
report.metrics.roc().plot()
```
=> fix(api): Do not call .plot() in display factory

skore/ci/pip-compile.sh
Currently, if the developer has some `pyenv` global settings or use `direnv`, we can't set the python version in a subshell to generate lockfiles. Instead, the developer python version is used silently.
---
We fix it by overloading `PYENV_VERSION`, which is the highest way to define the python version we want.
https://github.com/pyenv/pyenv/blob/master/COMMANDS.md#pyenv-shell
> Sets a shell-specific Python version by setting the PYENV_VERSION environment variable in your shell. This version overrides application-specific versions and the global version.
---
```diff
$ bash pip-compile.sh
Generating requirements: python==3.9 | scikit-learn==1.6 (1/6)
- Something wrong setting 'python-3.9', get '3.12'
```
```bash
$ bash pip-compile.sh
Generating requirements: python==3.9 | scikit-learn==1.6 …
```
=> ci: Ensure pyenv works when generating lockfiles

examples/getting_started/plot_quick_start.py, examples/technical_details/plot_cache_mechanism.py
Maybe due to the resolution of a merge conflict in #1299, it is missing some call to `.plot()`.
Here, we call explicitly and thus show the plot.
ping @thomass-dev
=> docs(fix): Explicitely call .plot() in example to show the output

sphinx/_static/css/custom.css
Closes https://github.com/probabl-ai/skore/issues/1008
=> docs: Change colors of links

skore/src/skore/sklearn/_cross_validation/report.py, skore/src/skore/sklearn/_estimator/report.py, skore/tests/unit/sklearn/test_cross_validation.py, skore/tests/unit/sklearn/test_estimator.py
This makes it more practical to print objects containing such reports,
e.g. `[report]`.
Closes #1293
=> feat: Change repr method of `EstimatorReport` and `CrossValidationReport`

.github/workflows/backend.yml
Cache venv using exact python version to fix failing pipelines https://github.com/probabl-ai/skore/actions/runs/13260129137/job/37014601717?pr=1305.
References:
https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#check-latest-version
https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#python-version
---
=> ci: Fix backend workflow to cache venv using exact python version

CONTRIBUTING.rst, sphinx/Makefile, sphinx/conf.py
You can now run `make html-noplot` to build the docs without building the examples.
Closes #1247
- Add Makefile target to avoid building examples
- Add redundant option in `sphinx/conf.py` to guide contributors
- Add documentation
=> docs: Add ways to avoid building examples

.gitignore, CONTRIBUTING.rst, sphinx/_static/css/custom.css, sphinx/conf.py, sphinx/index.rst, sphinx/reference/index.rst, sphinx/reference/project.rst, sphinx/reference/report.rst, sphinx/reference/report/cross_validation_report.rst, sphinx/reference/report/estimator_report.rst, sphinx/reference/report/index.rst
Our sphinx theme automatically adds dropdowns in the sidebar when the docs are nested in directories and subdirectories. This PR changes the structure of the docs to enable dropdowns.
One trade-off is that `toctree` and `autosummary` cannot both be used, so in the API index page, we no longer have a table-formatted list of all the public API functions and classes.
Before:
<image src="https://github.com/user-attachments/assets/0e547f3a-7b07-4f7a-be8e-79eb9e752a95" width="50%"></image>
After:
<image src="https://github.com/user-attachments/assets/385e8797-9791-49a4-b19c-c18bf6232c84" width="50%"></image>
Supersedes #1302
Closes #1095
Co-authored-by: Guillaume Lemaitre <guillaume@probabl.ai>
=> docs(api): Change structure to enable dropdowns in sidebar

skore/src/skore/project/project.py
closes #1326 
Fixing formatting in "Examples" section some method classes.
=> docs: Fix formatting of example section in docstring

skore/src/skore/sklearn/_plot/prediction_error.py, skore/tests/unit/sklearn/plot/test_prediction_error.py
closes #1292 
We forced the aspect ratio of 1.0 for the residual plot. However the residual is computing `actual vs predicted` and the scale of the residual can be really different from the prediction if the error is low, explaining the problem of the plot.
This PR only set the aspect ratio for the actual vs predicted plot only.
=> fix: Do not use aspect ratio of 1 for residual plot

skore/pyproject.toml, skore/src/skore/__init__.py, skore/src/skore/_config.py, skore/src/skore/sklearn/_cross_validation/metrics_accessor.py, skore/src/skore/sklearn/_cross_validation/report.py, skore/src/skore/sklearn/_estimator/report.py, skore/src/skore/utils/_parallel.py, skore/src/skore/utils/_progress_bar.py, skore/tests/unit/test_config.py, sphinx/reference/index.rst, sphinx/reference/utils.rst
closes #1264 
Add a config management functions (i.e. `get_config`, `set_config` and `config_context`) to globally set up some behaviour. We first intend to disable the progress bar globally using this helper.
From scikit-learn, there are corner case to propagate such configuration in parallel processing. We therefore use the same pattern by implementing `Parallel` and `delayed` and propagate our configuration within those function.
=> feat: Add config manager to manage progress bar

skore/src/skore/__init__.py, skore/src/skore/sklearn/__init__.py, sphinx/reference/report/cross_validation_report.rst, sphinx/reference/report/displays.rst, sphinx/reference/report/index.rst
closes #1328 
Document the different displays since they are part of the public API.
=> docs: Document the different displays as part of public API

skore/src/skore/project/project.py
Follow-up #1333 
Avoid to execute the `project.put` and `project.get` in the docstring of `Project`.
=> docs: Avoid creating project in docstring

skore/src/skore/_config.py
From the example given in config_context, I understand that it is not global, as apposed to set_config, but rather a local behavior. Is it correct?  
In any case, the current docs is blurry to me, because it doesn't appear at first sight what is the difference between `set_config` and `config_context`.
=> docs: Change config_context docs

skore/src/skore/_config.py
This PR tries to disambiguate what we mean by "global" when it comes to the configuration setting.
In short global refer that we are going to dispatch the configuration to local threads or sub-process.
It is really different from the "local" meaning within the code impacted by the context manager.
=> docs: Fix the ambuiguity regarding global configuration

skore/sphinx-requirements.in
Originally addressed by @glemaitre.
> We should temporary pin sphinx to 8.1.3 when building the documentation. They released 3 hours ago and it broke our CI
> Basically, the autosummary extension is broken because the signature of this function was changed: [https://github.com/xarray-contrib/sphinx-autosummary-accessors/blob/b230c4ea37bf3c[…]8f3179093439001ca7d/sphinx_autosummary_accessors/autosummary.py](https://github.com/xarray-contrib/sphinx-autosummary-accessors/blob/b230c4ea37bf3cf9fd1128f3179093439001ca7d/sphinx_autosummary_accessors/autosummary.py#L22C5-L22C36)
Example of broken pipeline: https://github.com/probabl-ai/skore/actions/runs/13408165303/job/37452025719
=> ci: Fix temporarily the version of `sphinx` to `<8.2.0`

skore/src/skore/sklearn/_comparison/report.py
=> feat: Add cache_predictions method to ComparisonReport

examples/getting_started/plot_skore_getting_started.py, skore/src/skore/sklearn/__init__.py, skore/src/skore/sklearn/_comparison/metrics_accessor.py, skore/src/skore/sklearn/_comparison/precision_recall_curve_display.py, skore/src/skore/sklearn/_comparison/prediction_error_display.py, skore/src/skore/sklearn/_comparison/roc_curve_display.py, skore/src/skore/sklearn/_plot/precision_recall_curve.py, skore/src/skore/sklearn/_plot/prediction_error.py, skore/src/skore/sklearn/_plot/roc_curve.py, skore/tests/unit/sklearn/comparison/test_comparison.py, skore/tests/unit/sklearn/comparison/test_precision_recall_curve_display.py, skore/tests/unit/sklearn/comparison/test_prediction_error_display.py, skore/tests/unit/sklearn/comparison/test_roc_curve_display.py
Duplicate the plot classes for `ComparisonReport` use-cases:
- `RocCurveDisplay`,
- `PredictionRecallCurveDisplay`,
- `PredictionErrorDisplay`.
I've chosen to simplify a few things from the original classes, in particular by removing the user's ability to customize the plot.
The plot tests strictly compare pixel by pixel the matplotlib result with an expected image.
The next iteration should be to factorize these duplicated classes with the one in `skore.sklearn._plot`.
---
**Roc curves**
**PR curves**
**Prediction error curves**
=> feat: Add dedicated `Display` classes to ComparisonReport

.github/workflows/sphinx.yml
Removes the temporary fix introduced to download `skrub` resources when OpenML was inaccessible.
Removes `HOME` envar overload which modified the `pip-cache` directory used in the sphinx build action, which differed from the `pip-cache` directory used in the calling workflow causing [errors](https://github.com/probabl-ai/skore/actions/runs/13583937631/job/37974812004).
=> ci: Fix sphinx pipeline

.github/workflows/backend.yml
Missing in https://github.com/probabl-ai/skore/pull/1337, call `mypy` from `pre-commit` in the GH pipelines.
=> ci: Ensure mypy checks are valid

examples/skore_project/plot_tracking_items.py
The plotly figure is not displayed:
=> docs: Fix `plot_tracking_items.py` for figure display

skore/ci/requirements/python-3.10/scikit-learn-1.6/test-requirements.txt, skore/ci/requirements/python-3.11/scikit-learn-1.6/test-requirements.txt, skore/ci/requirements/python-3.12/scikit-learn-1.4/test-requirements.txt, skore/ci/requirements/python-3.12/scikit-learn-1.5/test-requirements.txt, skore/ci/requirements/python-3.12/scikit-learn-1.6/test-requirements.txt, skore/ci/requirements/python-3.9/scikit-learn-1.6/test-requirements.txt, skore/pyproject.toml, skore/src/skore/_config.py, skore/src/skore/project/project.py, skore/src/skore/sklearn/train_test_split/train_test_split.py, skore/src/skore/utils/_show_versions.py
The PR introduces a new test dependency, [xdoctest](https://github.com/Erotemic/xdoctest), a modern rewrite of `doctest`. xdoctest makes it possible to apply a (x)doctest directive to all following lines. Example from [xdoctest's own docs](https://xdoctest.readthedocs.io/en/latest/auto/xdoctest.directive.html):
```python
>>> # An inline directive appears on the same line as a command and
>>> # only applies to the current line.
>>> raise AssertionError('this will not be run (a)')  # xdoctest: +SKIP
>>> print('This line will print: (A)')
>>> print('This line will print: (B)')
>>> # However, if a directive appears on its own line, then it applies
>>> # too all subsequent lines.
>>> # xdoctest: +SKIP()
>>> raise AssertionError('this will not be run (b)')
>>> print('This line will not print: …
```
=> test: Make it possible to ignore a whole block of doctests

.github/workflows/sphinx.yml
The root `/` URL wasn't purged. So the redirection from `/` to the newest release done by the `index.html` file wasn't effective until the CDN cache was revoked by its policy.
After a new release, we purge now the entire CDN cache.
=> ci: Fix CDN pruning when deploying root files in sphinx pipeline

.github/ISSUE_TEMPLATE/blank_issue.yml
Today blank issue template is not displayed, because description and body are mandatory keys (cf [doc I hadn't find before](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms#top-level-syntax)).
=> chore: Complete blank issues

Makefile, skore/pyproject.toml
Closes #1426   
Add 2 dependencies to be able to run .py examples locally in the IDE.
=> chore: Add dependencies for docs

skore/src/skore/sklearn/_estimator/metrics_accessor.py, skore/tests/unit/sklearn/estimator/test_estimator.py
Make `EstimatorReport.compute_metric_scores` return metrics in native types, for consistency across functions.
Allow metrics to be JSONable as is.
=> fix: Make `EstimatorReport.compute_metric_scores` return metrics in native types

.github/ISSUE_TEMPLATE/config.yml, sphinx/conf.py
Fix a couple of links in the documentation that did not use the canonical URL to our discord server.
=> docs: Discord link fix

examples/model_evaluation/plot_estimator_report.py, skore/src/skore/sklearn/train_test_split/train_test_split.py, skore/tests/unit/sklearn/train_test_split/test_train_test_split.py
Adds enhancement based on #1453.
I deviate from what is asked in #1453 and add a boolean argument `return_dict` that returns a dictionary if `True`. If required, I can change it into a wrapper instead but this should not break any code base per se.
What was done?
```python
from skore import train_test_split
from skore import EstimatorReport
import numpy as np
def main():
X, y = np.arange(10).reshape((5, 2)), range(5)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
my_dict = train_test_split(X,y, test_size=0.33,random_state=42, return_dict=True)
print(f"X_train: {X_train}\n X_test:{X_test}\n y_train:{y_train}\n y_test:{y_test}")
print(my_dict)
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier()
report = EstimatorReport(mlp, …
```
=> feat(train_test_split): Add optional argument to return dict

skore/src/skore/sklearn/_cross_validation/metrics_accessor.py, skore/src/skore/sklearn/_estimator/metrics_accessor.py, skore/src/skore/utils/_accessor.py, skore/tests/unit/sklearn/estimator/test_estimator.py, skore/tests/unit/sklearn/test_cross_validation.py
closes #1470 
This PR makes sure that a report exposes Brier score only if the estimator under the hood are exposing a `predict_proba` method.
=> fix: Do not expose Brier score if estimator does not implement predict_proba

skore/src/skore/sklearn/_estimator/metrics_accessor.py, skore/tests/unit/sklearn/estimator/test_estimator.py
closes #1501 
Fixing the regression described in #1501 where averaged score were falsely expected to be a `dict` instead of a `float`.
=> fix: Make sure that average != None return a float for metric

skore/src/skore/sklearn/_base.py, skore/src/skore/sklearn/_comparison/metrics_accessor.py, skore/src/skore/sklearn/_cross_validation/metrics_accessor.py, skore/src/skore/sklearn/_estimator/feature_importance_accessor.py, skore/src/skore/sklearn/_estimator/metrics_accessor.py, skore/src/skore/sklearn/_plot/utils.py, skore/tests/unit/sklearn/comparison/test_comparison.py, skore/tests/unit/sklearn/estimator/feature_importance/test_feature_importance.py, skore/tests/unit/sklearn/estimator/test_estimator.py, skore/tests/unit/sklearn/plot/test_common.py, skore/tests/unit/sklearn/test_cross_validation.py
closes #1236 
Formulate the sentence of the guidance using only "help() method" instead of fully qualified name with ambiguous variable name, e.g. "report.metrics.help()"
=> fix: Use a more general formulation for the rich repr

skore/src/skore/sklearn/find_ml_task.py, skore/src/skore/sklearn/types.py, skore/tests/unit/sklearn/test_utils.py
It is a bit weird to get an `unknown` type for `_find_ml_task` by providing an unfitted classifier and no target. We could instead return `classification`. We cannot infer better but it is more inline with whatever task we have at hand.
=> fix: Add classification type for _find_ml_task when y is unknown

skore/src/skore/sklearn/_estimator/metrics_accessor.py, skore/tests/unit/sklearn/comparison/test_comparison.py
closes #1396 
The private metric functions should be decorate as the public one such that we don't provide an unsupported metric for a class of estimators via the `report.metrics.report_metrics` method.
Note that one test was actually wrong. We needed to at least train the classifier to infer the proper ML task.
=> fix: Check if private metrics are available for an estimator

examples/technical_details/plot_cache_mechanism.py
closes #1216 
This PR will make two splits instead of a single one to have a completely left-out set to not have any confusion when we present the `data_source="X_y"` principle.
=> docs: Use left-out dataset for the external case in example

skore/src/skore/__init__.py, skore/src/skore/sklearn/_comparison/metrics_accessor.py, skore/src/skore/sklearn/_cross_validation/metrics_accessor.py, skore/src/skore/sklearn/_cross_validation/report.py, skore/src/skore/sklearn/_estimator/report.py, skore/src/skore/utils/_fixes.py, skore/tests/unit/test_at_import.py, skore/tests/unit/utils/test_fixes.py
closes #1452 
This PR introduces a way to be compatible with `joblib < 1.4` where `return_as` is not implemented. In this case, we can only use `list`.
The issue with using `list` is that we will be in degraded mode for the progress bars.
The proposal here is to:
- warn at import about the old `joblib` version and ask potentially to update it.
- disable the progress bar.
=> fix: Support joblib < 1.4 by using list container as output

sphinx/reference/report/comparison_report.rst, sphinx/reference/report/cross_validation_report.rst, sphinx/reference/report/estimator_report.rst
Adding two missing methods in the API documentation: `cache_predictions` and `clear_cache`.
=> docs: Add `cache_predictions` and `clear_cache` in API documentation

skore/src/skore/sklearn/_estimator/metrics_accessor.py, skore/src/skore/sklearn/_estimator/report.py, skore/tests/unit/sklearn/estimator/test_timings.py
While working on #1483, I realised that we are raising a pandas warning when a concatenation is done with fitted estimator in `report_metrics` because `fit_time=None` and `None` does not have the same `dtype` than other dataframe (`float`).
To avoid such issue, we can use `float("nan")` whenever we don't have the information and keep the `dtype` consistent. It will avoid the pandas warning as well.
In addition, I found a failure in #1483 in which, for some reason, the value of the hash of the data is changing. Therefore, I'm not hard-coding it anymore and instead computing on the go the value.
=> fix: Avoid pandas warning by using float('nan') instead of None

skore/src/skore/sklearn/_cross_validation/metrics_accessor.py, skore/src/skore/sklearn/_estimator/metrics_accessor.py, skore/src/skore/sklearn/_plot/metrics/prediction_error.py, skore/tests/unit/sklearn/plot/test_prediction_error.py
closes #1458 
This PR rename:
- `scatter_kwargs` to `data_points_kwargs`
- `line_kwargs` to `perfect_model_kwargs`
to align to the same naming semantic than with precision-recall or roc curve.
=> chore: Rename scatter_kwargs and line_kwargs in PredictionErrorDisplay

examples/getting_started/plot_skore_getting_started.py, examples/use_cases/plot_feature_importance.py, skore/src/skore/sklearn/_comparison/metrics_accessor.py, skore/src/skore/sklearn/_cross_validation/metrics_accessor.py, skore/src/skore/sklearn/_estimator/feature_importance_accessor.py, skore/src/skore/sklearn/_estimator/metrics_accessor.py, skore/src/skore/sklearn/_plot/metrics/prediction_error.py, skore/tests/unit/sklearn/estimator/feature_importance/test_permutation_importance.py, skore/tests/unit/sklearn/estimator/test_estimator.py, skore/tests/unit/sklearn/test_cross_validation.py
closes #1397 
This PR proposes to rename `random_state` handled by `skore` to `seed` since we can only support integral when it comes to caching.
=> chore: Rename random_state to seed to highlight int-only support

skore/src/skore/sklearn/_comparison/report.py, skore/src/skore/sklearn/_cross_validation/report.py, skore/src/skore/sklearn/_estimator/report.py, skore/tests/unit/sklearn/comparison/test_comparison.py, skore/tests/unit/sklearn/estimator/test_estimator.py, skore/tests/unit/sklearn/test_cross_validation.py, sphinx/reference/report/comparison_report.rst, sphinx/reference/report/cross_validation_report.rst, sphinx/reference/report/estimator_report.rst
Partially address #1417 by implementing `EstimatorReport.get_predictions` such that one can get the predictions from a model and eventually from the cache if it was already computed before.
=> feat: Add `get_predictions` method to all reporters

skore/src/skore/sklearn/_base.py, skore/src/skore/sklearn/_comparison/metrics_accessor.py, skore/src/skore/sklearn/_cross_validation/metrics_accessor.py, skore/src/skore/sklearn/_estimator/metrics_accessor.py, skore/src/skore/sklearn/_plot/utils.py, skore/tests/unit/sklearn/estimator/test_timings.py
closes #1466 
Use `typing.cast` when there is not real need for `assert` inside the source code.
=> chore: Use cast instead of assert when there is no need for defensive assert

skore/src/skore/sklearn/_cross_validation/metrics_accessor.py, skore/src/skore/utils/_accessor.py
closes #1472
Delegate the availability of all different methods from `CrossValidationReport` depending if they are available into the `EstimatorReport` from the first CV split.
=> chore: Delegate availability methods to underlying EstimatorReport

examples/getting_started/plot_quick_start.py, examples/getting_started/plot_skore_getting_started.py, examples/model_evaluation/plot_estimator_report.py, examples/technical_details/plot_cache_mechanism.py, examples/use_cases/plot_employee_salaries.py, examples/use_cases/plot_feature_importance.py, skore/src/skore/sklearn/_plot/metrics/precision_recall_curve.py, skore/src/skore/sklearn/_plot/metrics/prediction_error.py, skore/src/skore/sklearn/_plot/metrics/roc_curve.py, skore/src/skore/sklearn/_plot/style.py, skore/tests/unit/sklearn/plot/test_precision_recall_curve.py, skore/tests/unit/sklearn/plot/test_prediction_error.py, skore/tests/unit/sklearn/plot/test_roc_curve.py
closes #1457
closes #1201
closes #1456
This PR creates a context manager where we temporary increases the font size to have better styled figure and make sure to use `tight_layout` on the figure before to return. Additionally, we move the legend outside of the figure such that it is more readable
=> feat: Increase the font size, use `tight_layout`, and better legend location

skore/src/skore/sklearn/_plot/style.py, sphinx/conf.py, sphinx/sphinxext/matplotlib_skore_scraper.py
It looks that the `display.figure_.tight_layout()` does not work for the purpose of the documentation. I was looking within notebooks and VS code but forgot to check the website.
For the website, we can actually solve it by modifying the matplotlib scrappers from sphinx-gallery and fix pass the right parameter to `savefig`. I removed the "200 dpi" because it makes the figure too big and I don't think that the default quality is bad.
=> docs: Fix rendering using custom matplotlib scraper

skore/src/skore/sklearn/_estimator/metrics_accessor.py
Similarly to `EstimatorReport._fit_time`, putting `None` in a DataFrame makes pandas warn that this will be deprecated in the future.
=> refactor: Add `cast` argument to `EstimatorReport._predict_time`

skore/src/skore/sklearn/_comparison/metrics_accessor.py, skore/src/skore/sklearn/_cross_validation/metrics_accessor.py, skore/src/skore/utils/_progress_bar.py
This originates from a bug when implementing comparison of CrossValidationReport in #1512 
Because CrossValidationReports hold a `_parent_progress`, when a ComparisonReport creates a progress bar to iterate over CrossValidationReports, the outer progress bar conflicts with the inner progress bars, and rich refuses to proceed.
The solution is for the ComparisonReport to explicitly set its inner CrossValidationReports' progress instance, so that in total there is only one progress instance.
But before this change, the progress instance was sometimes owned by a `CrossValidationReport.metrics` accessor. This is a problem because accessors are re-instantiated whenever they are accessed, so their state cannot be modified from the parent.
The solution this change implements is to remove all …
=> refactor(progress_decorator): Make sure `self_obj` is a `Report`

examples/use_cases/plot_employee_salaries.py
Closes https://github.com/probabl-ai/skore/issues/1505.
I have made the changes as discussed in the issue's comments. I created the docs locally and aesthetically they looked fine. Will double check with the CI/CD docs build and adjust upon comments/questions.
I had a small question regarding the variable names: hgbdt_model_report and linear_model_report. They’re definitely descriptive, but I was wondering if they might be a bit confusing for someone newer to machine learning. Since linear models are typically taught early on, they’re often seen as more "basic," whereas an abbreviation like hgbdt could feel a little intimidating if someone isn’t already familiar with it.
I know the models are explained well in the Modelling section, so it’s probably fine — I just wanted to check if you …
=> docs: Show simpler model first and complex second in example use case

examples/getting_started/plot_skore_getting_started.py, examples/model_evaluation/plot_train_test_split.py
Closes #1504.
I simply inspected the `X_employee["date_first_hired"]` series by printing it, and saw that it uses the `mm/dd/yyyy` format. I have updated both examples to use the corresponding format argument.
The linked issue also mentions `skrub.ToDatetime` but I am not clear on what exactly is to be done with that. It looks like that API is only used in one example: `examples/use_cases/plot_employee_salaries.py`. If anyone can clarify what needs to be done I would love to take it up in this PR or a future PR.
=> docs: Pass format to `pd.to_datetime`

.github/workflows/sphinx.yml
Merge the two different steps that purge the CDN into a single job:
- the one purging a specific documentation version when deploying its HTML files (especially on `dev`),
- the one purging the entire CDN when changing the root files (especially `index.html`).
Even if it is less efficient to purge the entire CDN instead of purging specific versions on demand, the CI is easier to maintain.
=> ci: Factorize the jobs that prune the CDN cache

skore/src/skore/sklearn/_cross_validation/metrics_accessor.py, skore/src/skore/sklearn/_cross_validation/report.py, skore/src/skore/sklearn/_estimator/metrics_accessor.py, skore/src/skore/sklearn/_estimator/report.py, skore/src/skore/sklearn/_plot/metrics/precision_recall_curve.py, skore/src/skore/sklearn/_plot/metrics/prediction_error.py, skore/src/skore/sklearn/_plot/metrics/roc_curve.py, skore/tests/unit/sklearn/plot/test_precision_recall_curve.py, skore/tests/unit/sklearn/plot/test_prediction_error.py, skore/tests/unit/sklearn/plot/test_roc_curve.py, skore/tests/unit/sklearn/test_cross_validation.py
closes #1500 
Allow to pass `data_source="X_y"` to make underlying estimator predict on the same set with `CrossValidationReport`.
=> feat: Enable data_source=X_y in CrossValidationReport

.gitignore, .pre-commit-config.yaml, skore/ci/requirements/python-3.10/scikit-learn-1.6/test-requirements.txt, skore/ci/requirements/python-3.11/scikit-learn-1.6/test-requirements.txt, skore/ci/requirements/python-3.12/scikit-learn-1.4/test-requirements.txt, skore/ci/requirements/python-3.12/scikit-learn-1.5/test-requirements.txt, skore/ci/requirements/python-3.12/scikit-learn-1.6/test-requirements.txt, skore/ci/requirements/python-3.9/scikit-learn-1.6/test-requirements.txt, skore/hatch/metadata.py, skore/pyproject.toml, skore/src/skore/project/project.py, skore/src/skore/sklearn/_estimator/report.py
Some minor changes to prepare for the arrival of the new package `skore-remote-project`:
- Add reference to the new package `skore-remote-project` in `.gitignore` and `pre-commit` configuration,
- Remove deprecated code from `skore`,
- Add a new `ml_task` property in the `skore.EstimatorReport` class.
=> feat: Draft the new package `skore-remote-project`

examples/use_cases/plot_feature_importance.py
This pull request fixes a duplicate target name warning that came up during the make html process (see issue #1202).
The warning was caused by two hyperlinks having the same display text. 
"...We consider a linear model as defined in scikit-learn's user guide <https://scikit-learn.org/stable/modules/linear_model.html>."
"...For more information, see scikit-learn's user guide <https://scikit-learn.org/stable/modules/permutation_importance.html#misleading-values-on-strongly-correlated-features>."
<br>
```python
skore/sphinx/auto_examples/use_cases/plot_feature_importance.rst:25: WARNING: Duplicate explicit target name: "scikit-learn's user guide". [docutils]
```
---
- Model: Dell Latitude E7440
- RAM: 12GB 
- OS: Windows 10 pro
- Python Version: Python 3.12
- Terminal: Ubuntu 22.04 LTS
--- …
=> docs: Fix duplicate target name warning during sphinx build

.github/workflows/backend.yml
Fix `backend-lockfiles` job which no longer works since we deleted the `requirements.ini` https://github.com/probabl-ai/skore/pull/1418.
Examples showing that this PR works:
- [Commit](https://github.com/probabl-ai/skore/pull/1595/commits/bde257d5aa67ad6a0c3e20d8ec19f53ad7acd708) showing a red pipeline, with a change on `pyproject.toml` without requirements update,
- [Commit](https://github.com/probabl-ai/skore/pull/1595/commits/25cb3c8588f536034dd9c88fec91d270ab334bbf) showing a green pipeline, with a change on `pyproject.toml` and requirements update.
=> ci: Fix `backend-lockfiles` job after the removal of `requirements.ini` files

skore/src/skore/sklearn/train_test_split/warning/high_class_imbalance_too_few_examples_warning.py, skore/src/skore/sklearn/train_test_split/warning/high_class_imbalance_warning.py
the `cross_validation` function doesn't exist anymore. It was replace in PR https://github.com/probabl-ai/skore/pull/847 with the `CrossValidationReport` class. Please let me know if this change LGTY-- or should I've replaced "skore's `cross_validation` function." with something in sklearn (e.g. - this page: https://scikit-learn.org/stable/modules/cross_validation.html#cross-validation)?
Thank you :)
=> chore: Replace `cross_validation` with `CrossValidationReport` in warnings

skore/src/skore/sklearn/_estimator/feature_importance_accessor.py, skore/src/skore/utils/_accessor.py, skore/tests/unit/sklearn/estimator/feature_importance/conftest.py, skore/tests/unit/sklearn/estimator/feature_importance/test_coefficients.py, skore/tests/unit/utils/test_accessors.py
closes issue https://github.com/probabl-ai/skore/issues/1364
- incorporated:
- other changes: 
- need feedback on:
Thanks :)
=> test: Include all estimators (with `coef_`) in `test_all_sklearn_estimators`

.github/workflows/lint.yml, .github/workflows/skore-remote-project.yml, .github/workflows/skore.yml
**Context:**
Linting must be run on `/skore/`, `/skore-remote-project/` and `/examples/`.
```yml
- name: Lint
working-directory: skore-remote-project/
run: |
pre-commit run --all-files ruff
pre-commit run --all-files mypy
```
```yml
- name: Lint
working-directory: skore/
run: |
pre-commit run --all-files ruff
pre-commit run --all-files mypy
```
These snippets will not only run on `/skore/` or `/skore-remote-project`, but both on `/`.
So the `ruff` and `mypy` linting will be executed twice in integrality.
Wherever `pre-commit run --all-files` is executed, it will be execute from the root of the repository.
---
**Solution:**
One solution is to fix the command to run linting only on the wanted repository.
```yml
- name: Lint
working-directory: skore-remote-project/
run: |
git ls-files | …
```
=> ci: Factorize lint jobs

sphinx/index.rst
Pausible was already activated
```python
html_theme_options["analytics"] = {                                
"plausible_analytics_domain": domain,                          
"plausible_analytics_url": "https://plausible.io/js/script.js",
}                                                                  
```
This reverts commit 867f007f0454fdda16a7db8f0dad3ce74015ed93.
=> Revert "docs: Add Plausible tracker (#1605)"

.github/workflows/pr-display-code-coverage.yml, .github/workflows/skore-remote-project.yml, .github/workflows/skore.yml
This robustly solves an issue with the coverage report message action. See https://github.com/MishaKav/pytest-coverage-comment/issues/202 for more context.
Additionally, make sure that each project in the repo (i.e. skore and skore-remote-project) has its own coverage message.
Co-authored-by: Thomas S <thomas@probabl.ai>
=> ci(coverage-report): Produce XML coverage report rather than plain text

examples/use_cases/plot_feature_importance.py
Closes [#1587](https://github.com/probabl-ai/skore/issues/1587)
Hi @sylvaincom  , @thomass-dev  !
I updated the deprecated `scatter_mapbox` function and have now replaced it with the  more updated `scatter_map`.
On another note, in the feature selection pipeline scikit-learn's `SelectKBest` was seeing features with zero variance which raised division-by-zero errors during computation of feature importance. 
I have added a `VarianceThreshold` filter to eliminate near zero variance features prior to the feature selection process.
=> docs: Replace `scatter_mapbox` with `scatter_map` and handle zero-variance case in `SelectKBest`

skore/src/skore/sklearn/_comparison/metrics_accessor.py, skore/src/skore/sklearn/_comparison/report.py, skore/src/skore/sklearn/_comparison/utils.py, skore/src/skore/sklearn/_cross_validation/report.py, skore/src/skore/utils/_testing.py, skore/tests/unit/sklearn/comparison/conftest.py, skore/tests/unit/sklearn/comparison/cross_validation/test_metrics.py, skore/tests/unit/sklearn/comparison/cross_validation/test_report.py, skore/tests/unit/sklearn/comparison/cross_validation/test_report_metrics.py, skore/tests/unit/sklearn/comparison/estimator/test_comparison.py, skore/tests/unit/sklearn/comparison/test_report_common.py, skore/tests/unit/sklearn/cross_validation/test_cross_validation.py, skore/tests/unit/sklearn/estimator/feature_importance/test_permutation_importance.py
This PR makes it possible to pass a list of `CrossValidationReport`s to the `ComparisonReport` (which currently only accepts `EstimatorReport`s).
For now, plots like `Comparison.metrics.roc_curve` are not supported for ComparisonReports holding CrossValidationReports.
---
Example:
```python
>>> from sklearn.datasets import make_classification
>>> from sklearn.linear_model import LogisticRegression
>>> from skore import ComparisonReport, CrossValidationReport
>>> X, y = make_classification(random_state=42)
>>> estimator_1 = LogisticRegression()
>>> estimator_2 = LogisticRegression(C=2)  # Different regularization
>>> report_1 = CrossValidationReport(estimator_1, X, y)
>>> report_2 = CrossValidationReport(estimator_2, X, y)
>>> report = ComparisonReport({"model1": report_1, "model2": …
```
=> feat: Compare `CrossValidationReport`s

skore-remote-project/src/skore_remote_project/item/item.py, skore-remote-project/src/skore_remote_project/item/matplotlib_figure_item.py, skore-remote-project/src/skore_remote_project/item/skore_estimator_report_item.py, skore-remote-project/src/skore_remote_project/item/skrub_table_report_item.py, skore-remote-project/tests/conftest.py, skore-remote-project/tests/unit/item/test_matplotlib_figure_item.py, skore-remote-project/tests/unit/item/test_skrub_table_report_item.py
> [!IMPORTANT]
> skore-remote-project
Fix [flaky pipeline](https://github.com/probabl-ai/skore/actions/runs/14732548381/job/41350256575#step:10:392) by setting `matplotlib.backend` to `agg` during artifacts generation, and force it in tests.
Reference:
https://github.com/matplotlib/matplotlib/issues/29119
https://matplotlib.org/stable/users/explain/figure/backends.html#selecting-a-backend
=> fix: Set `matplotlib.backend` to `agg` during artifacts generation

skore/src/skore/sklearn/_estimator/feature_importance_accessor.py, skore/tests/unit/sklearn/estimator/feature_importance/test_coefficients.py
followup for PR https://github.com/probabl-ai/skore/pull/1575
=> test: Adapt `coefficients()` logic for meta-estimators

.github/actions/sphinx/build/action.yml, Makefile, ci/pip-compile.sh, skore-remote-project/pyproject.toml, skore/pyproject.toml
Install `polars-lts-cpu` on demand: not all `x86_64` platform need this version of `polars`, only the **old** ones.
Fixing https://github.com/probabl-ai/skore/issues/1567 and https://github.com/probabl-ai/skore/pull/1568.
=> fix: Do not force installation of `polars-lts-cpu` on `x86_64` platform

skore/src/skore/persistence/storage/disk_cache_storage.py
Fixes failing pipelines from https://github.com/probabl-ai/skore/pull/1617.
---
https://grantjenks.com/docs/diskcache/tutorial.html#settings
https://grantjenks.com/docs/diskcache/tutorial.html#eviction-policies
```
size_limit, default one gigabyte. The maximum on-disk size of the cache.
cull_limit, default ten. The maximum number of keys to cull when adding a new item. 
Set to zero to disable automatic culling.
eviction_policy, default “least-recently-stored”. The setting to determine [eviction policy](https://grantjenks.com/docs/diskcache/tutorial.html#tutorial-eviction-policies).
"none" disables cache evictions. Caches will grow without bound.
```
=> fix: Set size limit of `DiskCacheStorage` from 1go to unlimited

skore/src/skore/_config.py, skore/src/skore/sklearn/_comparison/metrics_accessor.py, skore/src/skore/sklearn/_comparison/report.py, skore/src/skore/sklearn/_estimator/feature_importance_accessor.py, skore/src/skore/sklearn/_estimator/metrics_accessor.py, skore/src/skore/sklearn/_estimator/report.py, skore/src/skore/sklearn/_plot/metrics/precision_recall_curve.py, skore/src/skore/sklearn/_plot/metrics/prediction_error.py, skore/src/skore/sklearn/_plot/metrics/roc_curve.py, skore/src/skore/sklearn/train_test_split/train_test_split.py
Fixes #1503
Related to #1643 but might be more exhaustive in refactoring docstring examples.
After this commit there should be no more `>>> X_train, X_test, y_train, y_test = train_test_split(...)` in the docstrings.
=> refactor: Use `skore.train_test_split(..., as_dict=True)` in all examples

skore/src/skore/sklearn/_comparison/report.py, skore/tests/unit/sklearn/comparison/estimator/test_comparison.py
Closes [#1621](https://github.com/probabl-ai/skore/issues/1621)
Hi @auguste-probabl  , @thomass-dev  !
`ComparisonReport` now only checks `y_test` consistency, enabling comparison of models with different feature sets.
Thank You!
=> fix(ComparisonReport): Only check `y_test`

skore/src/skore/sklearn/_comparison/metrics_accessor.py, skore/src/skore/sklearn/_comparison/report.py
This PR addresses the `Inline interpreted text or phrase reference start-string without end-string` warnings encountered during the Sphinx `make html` build process (Issue #1671).
These warnings occurred because of a reference that starts with a backtick but doesn't have a matching closing backtick in the docstring.
```python   
~/_comparison/report.py:docstring of skore.sklearn._comparison.report.ComparisonReport:4: WARNING: Inline interpreted text or phrase reference start-string without end-string. [docutils]
~/_comparison/report.py:docstring of skore.sklearn._comparison.report.ComparisonReport:4: WARNING: Inline interpreted text or phrase reference start-string without end-string. [docutils]
~/_comparison/metrics_accessor.py:docstring of …
```
=> docs: Resolve `Inline interpreted text [...] without end-string` warnings

skore/src/skore/sklearn/_comparison/report.py, skore/src/skore/sklearn/_cross_validation/report.py, skore/src/skore/sklearn/_estimator/report.py, skore/src/skore/utils/_progress_bar.py, skore/tests/unit/utils/test_progress_bar.py
Closes #1620
Refactored to use a single attribute `_progress_info` for all progress bar handling, eliminating the redundant `_parent_progress` attribute.
- Removed initialization of `_parent_progress` from all report classes: EstimatorReport, CrossValidationReport, ComparisonReport.
- Modified the `progress_decorator` to check only for `_progress_info` attribute instead of checking for both attributes (`_parent_progress` and `_progress_info`).
- When sharing a progress bar from parent to child reports, we have this now:
```python
child._progress_info = {"current_progress": progress}
```
instead of this before:
```python
child._parent_progress = progress
```
=> refactor: Remove `_parent_progress` attribute

.github/actions/sphinx/build/action.yml, CONTRIBUTING.rst, Makefile, ci/pip-compile.sh, skore-remote-project/pyproject.toml, skore/pyproject.toml
Following https://github.com/probabl-ai/skore/pull/1618:
- Add a new target to install `skore` on LTS CPU,
- Make `test`/`sphinx` optional dependencies self-sufficient.
=> feat: Add `Makefile/make-install-skore-lts-cpu` target

skore/src/skore/sklearn/_cross_validation/metrics_accessor.py
This PR addresses the `Bullet list ends without a blank line; unexpected unindent. [docutils]` warnings encountered during the Sphinx `make html` build process (Issue #1671).
These warnings occurred because a section was not properly indented in the code, and there was no blank line after a bulleted list.
```python   
~/src/skore/sklearn/_cross_validation/metrics_accessor.py:docstring of skore.sklearn._cross_validation.metrics_accessor._MetricsAccessor.roc:15: WARNING: Bullet list ends without a blank line; unexpected unindent. [docutils]
```
---
- Model: Dell Latitude E7440
- RAM: 12GB 
- OS: Windows 10 pro
- Python Version: Python 3.12
- Terminal: Ubuntu 22.04 LTS
---
1. Clone the skore repository
2. Create and activate a virtual environment using the Ubuntu terminal
3. Run the _make …
=> docs: Resolve `Bullet list [..], unexpected unindent` warnings

sphinx/_templates/base.rst
This PR addresses the `duplicate object description` warnings encountered during the Sphinx `make html` build process (Issue #1202).
These warnings occurred because some object descriptions were documented in multiple places (the manual .rst files, and automatically generated ones), which caused Sphinx to index the same object multiple times.
```python
skore/skore/src/skore/sklearn/_comparison/report.py:docstring of skore.sklearn._comparison.report.ComparisonReport.cache_predictions:1: WARNING: duplicate object description of skore.ComparisonReport.cache_predictions, other instance in reference/api/skore.ComparisonReport, use :no-index: for one of them
skore/skore/src/skore/sklearn/_comparison/report.py:docstring of skore.sklearn._comparison.report.ComparisonReport.clear_cache:1: WARNING: …
```
=> docs: Resolve `duplicate object description` warnings

skore/src/skore/sklearn/_plot/metrics/roc_curve.py, skore/tests/unit/sklearn/plot/test_roc_curve.py
The chance level line label now appears in the legend.
Before/After:
---
Depends on #1668
=> fix(roc-curve): Show chance level in the legend

.github/workflows/release.yml, .github/workflows/sphinx.yml
Change release workflow to release `skore|skore-(local|remote)-project` package.
Tags must be prefixed by package:
- `p-a-c-k-a-g-e/X.Y.Z`     
- `p-a-c-k-a-g-e/X.Y.Z-rc.A`
Examples of valid tags: `skore/1.0.0`, `skore-local-project/0.0.1`.
---
Various:
- name artifacts in `release.yml` using UUID to allow parallel releases,
- deploy documentation in `sphinx.yml` only on `skore` tags (and not RC).
=> ci: Change workflow to release `skore|skore-(local|remote)-project`

skore/src/skore/sklearn/_comparison/metrics_accessor.py, skore/src/skore/sklearn/_cross_validation/metrics_accessor.py, skore/src/skore/sklearn/_estimator/metrics_accessor.py, skore/tests/unit/sklearn/cross_validation/test_cross_validation.py, skore/tests/unit/sklearn/estimator/test_estimator.py
closes https://github.com/probabl-ai/skore/issues/1715
closes #1714
closes https://github.com/probabl-ai/skore/pull/1716
closes https://github.com/probabl-ai/skore/issues/1686
This PR:
- fixes the way we handle scikit-learn scorer names
- update the API documentation to provide the difference between built-in metrics and scikit-learn scorer names
- fixes the tests that are available
- add more tests for metrics that takes additional parameters
=> fix: Leverage `get_scorer` and the fact it is a `_BaseScorer`

sphinx/Makefile, sphinx/_templates/base.rst, sphinx/reference/report/index.rst
This fixes an issue where internal links to API docs were no longer recognized as links.
The bug originates from https://github.com/probabl-ai/skore/commit/830f2614ee943a853165bceba048c2eae856c1d8, which intended to remove sphinx warnings about "duplicate object descriptions".
https://github.com/sphinx-doc/sphinx/issues/8664 discusses these warnings, and applying the solution described in https://github.com/sphinx-doc/sphinx/issues/8664#issuecomment-757087741 resolves the issue (warnings disappear and links still work).
=> docs: Fix internal links

skore/src/skore/sklearn/_comparison/utils.py, skore/tests/unit/sklearn/comparison/cross_validation/test_report_metrics.py
Closes #1706
Closes #1704
The issue is a consequence of pandas DataFrame mutability.
Specifically, `_combine_cross_validation_results` manipulates
a list of DataFrames mutably, and since the DataFrames come
from a cache (which is a mutable dict), the DataFrames inside
the cache end up mutated.
https://github.com/probabl-ai/skore/blob/9bbfdb34fc8a62555aa8d3cc79a8f914dd22dd43/skore/src/skore/sklearn/_comparison/metrics_accessor.py#L250
`_combine_cross_validation_results` already performs a copy
of its input (a list of DataFrames) to prevent this sort of problem,
but apparently this is not enough: the copied list still references
the same DataFrames.
https://github.com/probabl-ai/skore/blob/9bbfdb34fc8a62555aa8d3cc79a8f914dd22dd43/skore/src/skore/sklearn/_comparison/utils.py#L295
=> fix(Comparison[CVReport]): Avoid mutating DataFrames in cache

skore/src/skore/sklearn/_estimator/metrics_accessor.py, skore/tests/unit/sklearn/estimator/test_estimator.py
closes https://github.com/probabl-ai/skore/issues/1736
This PR is making sure that we expose the `log_loss` only for estimator exposing a `predict_proba` method.
=> fix: Log loss only available with estimator exposing predict_proba

skore/src/skore/project/project.py, skore/src/skore/sklearn/_comparison/report.py, skore/src/skore/sklearn/_cross_validation/report.py, skore/src/skore/sklearn/_estimator/report.py, sphinx/_templates/autosummary/accessor.rst, sphinx/_templates/base.rst, sphinx/_templates/class_methods_no_index.rst, sphinx/reference/project.rst, sphinx/reference/report/comparison_report.rst, sphinx/reference/report/cross_validation_report.rst, sphinx/reference/report/estimator_report.rst
This PR tries to solve the issues regarding the warning raised by `sphinx`, e.g.
```
/Users/xxx/skore/src/skore/project/project.py:docstring of skore.Project.reports:1: WARNING: duplicate object description of skore.Project.reports, other instance in api/skore.Project.reports, use :no-index: for one of them
```
It solves as well a couple rendering issues spotted when debugging. It remains a single warning due to the `skore.Project` class but the current solution in conjunction with the changes proposed in https://github.com/probabl-ai/skore/pull/1740 will solve the issue.
=> chore: Fix warning in sphinx about duplicate object

skore/src/skore/project/__init__.py, skore/src/skore/project/project.py, skore/src/skore/project/reports.py, skore/tests/unit/project/test_project.py, sphinx/reference/project.rst
Change `Project.reports` from `types.SimpleNamespace` to `pandas` style accessor, to let sphinx documents:
- `Project.reports.get`
- `Project.reports.metadata`
=> docs(skore): Add Project.reports methods to the documentation

skore/src/skore/sklearn/_estimator/report.py
We see some flakyness in https://github.com/probabl-ai/skore/actions/runs/15188333231/job/42714438658?pr=1593
I'm thinking that it could be due to this code: since we have a generator, we can modify `self._cache` before/during that it is consume by `Parallel`, making the pickling of the task to fail.
Let's see if it works.
=> fix: Make sure to not mutate cache during Parallel processing

skore/src/skore/sklearn/train_test_split/train_test_split.py, skore/tests/unit/sklearn/train_test_split/test_train_test_split.py
Fixes #1544.
- Allows the user to specify X and y positional arguments. 
- Warn users that single/double positional arguments default to 'X'/'y' names when as_dict=True.
- Updated docstrings.
- Added new and fixed old tests.
=> feat(train_test_split): Allow positional arguments with `as_dict=True`

README.md, skore/pyproject.toml, sphinx/index.rst
Update README with new tagline.
Update README after the drop of the support of `python==3.9` and the add of the support of `scikit-learn==1.7`.
Closes https://github.com/probabl-ai/skore/issues/1828.
Following https://github.com/probabl-ai/skore/pull/1827 and https://github.com/probabl-ai/skore/pull/1829.
=> feat(skore): Update README with new tagline

ci/requirements/skore-hub-project/python-3.10/scikit-learn-1.4/test-requirements.txt, ci/requirements/skore-hub-project/python-3.10/scikit-learn-1.7/test-requirements.txt, ci/requirements/skore-hub-project/python-3.11/scikit-learn-1.4/test-requirements.txt, ci/requirements/skore-hub-project/python-3.11/scikit-learn-1.7/test-requirements.txt, ci/requirements/skore-hub-project/python-3.12/scikit-learn-1.7/test-requirements.txt, ci/requirements/skore-hub-project/python-3.13/scikit-learn-1.5/test-requirements.txt, ci/requirements/skore-hub-project/python-3.13/scikit-learn-1.6/test-requirements.txt, ci/requirements/skore-hub-project/python-3.13/scikit-learn-1.7/test-requirements.txt, ci/requirements/skore/python-3.10/scikit-learn-1.4/test-requirements.txt, ci/requirements/skore/python-3.10/scikit-learn-1.7/test-requirements.txt, ci/requirements/skore/python-3.11/scikit-learn-1.4/test-requirements.txt, ci/requirements/skore/python-3.11/scikit-learn-1.7/test-requirements.txt, ci/requirements/skore/python-3.12/scikit-learn-1.4/test-requirements.txt, ci/requirements/skore/python-3.12/scikit-learn-1.7/test-requirements.txt, ci/requirements/skore/python-3.13/scikit-learn-1.5/test-requirements.txt, ci/requirements/skore/python-3.13/scikit-learn-1.6/test-requirements.txt, ci/requirements/skore/python-3.13/scikit-learn-1.7/test-requirements.txt
Following https://github.com/probabl-ai/skore/pull/1850, and to close dependabot security issues.
Bumps the pip group with 1 update in the /ci/requirements/skore-hub-project/python-3.10/scikit-learn-1.4 directory: [urllib3](https://github.com/urllib3/urllib3).
Bumps the pip group with 1 update in the /ci/requirements/skore-hub-project/python-3.10/scikit-learn-1.7 directory: [urllib3](https://github.com/urllib3/urllib3).
Bumps the pip group with 1 update in the /ci/requirements/skore-hub-project/python-3.11/scikit-learn-1.4 directory: [urllib3](https://github.com/urllib3/urllib3).
Bumps the pip group with 1 update in the /ci/requirements/skore-hub-project/python-3.11/scikit-learn-1.7 directory: [urllib3](https://github.com/urllib3/urllib3).
Bumps the pip group with 1 update in the …
=> chore(deps): Bump urllib3 in lockfiles

Makefile
@sylvaincom had troubles caused by the non-automatic update of `skore-local-project`.
=> fix(skore): Force the upgrade of python dependencies on `make install-skore`

sphinx/user_guide/reporters.rst
The $X_{test}$ math notation wasn't showing properly in the [Structuring Data Science -> Comparison Report section](https://docs.skore.probabl.ai/dev/user_guide/reporters.html#comparison-report)
=> docs: Fix math notation in the `Comparison report` section of the user guide

skore-hub-project/src/skore_hub_project/project/artefact.py, skore-hub-project/src/skore_hub_project/project/project.py, skore-hub-project/tests/unit/project/test_artefact.py, skore-hub-project/tests/unit/project/test_project.py
Closes https://github.com/probabl-ai/skore/issues/1910.
---
Tested both on linux and windows.
Tested across scripts, IPython and notebooks.
Also, i tested other back-ends to parallelize IO:
- `asyncio`, issues with notebooks,
- `asyncio` x `threading` (use new event loop in a dedicated thread), works, but i decided to use only `threading` for simplicity,
- `anyio`, same issues as `asyncio`,
- `trio`, lower performance that `threading`.
https://github.com/user-attachments/assets/a20169a9-405f-4350-bff1-d9eb7d940e1e
=> feat(skore-hub-project): Send a heavy report in several chunks

sphinx/user_guide/index.rst
- Replace 'refer to' with descriptive text 'skrub's documentation'
- Improves readability and user experience in the user guide
- Updated `sphinx/user_guide/index.rst` line 13
- Changed hyperlink from generic 'refer to' to descriptive 'skrub's documentation'
- ✅ Documentation builds successfully with `make html-noplot`
- ✅ Pre-commit hooks pass
Fixes #1860
=> docs: Improve hyperlink text in user guide

examples/getting_started/plot_skore_getting_started.py, examples/technical_details/plot_cache_mechanism.py, examples/use_cases/plot_employee_salaries.py, skore/src/skore/_config.py, skore/src/skore/_sklearn/_cross_validation/metrics_accessor.py, skore/src/skore/_sklearn/_cross_validation/report.py, skore/src/skore/_sklearn/train_test_split/warning/high_class_imbalance_too_few_examples_warning.py, skore/src/skore/_sklearn/train_test_split/warning/high_class_imbalance_warning.py, skore/tests/unit/sklearn/comparison/cross_validation/test_metrics.py, skore/tests/unit/sklearn/comparison/cross_validation/test_report.py, skore/tests/unit/sklearn/comparison/cross_validation/test_report_metrics.py, skore/tests/unit/sklearn/cross_validation/test_cross_validation.py, skore/tests/unit/sklearn/plot/precision_recall_curve/test_comparison_cross_validation.py, skore/tests/unit/sklearn/plot/precision_recall_curve/test_cross_validation.py, skore/tests/unit/sklearn/plot/prediction_error/test_comparison_cross_validation.py, skore/tests/unit/sklearn/plot/prediction_error/test_cross_validation.py, skore/tests/unit/sklearn/plot/roc_curve/test_comparison_cross_validation.py, skore/tests/unit/sklearn/plot/roc_curve/test_cross_validation.py
> [!CAUTION]
> Must be merged after https://github.com/probabl-ai/skore/issues/1955.
> Can i rename `cv_splitter` in `splitter` 👼🏻 ?
> It looks obvious that splitter in the `CrossValidationReport` is the splitter of the cross-validation.
_Originally posted by @thomass-dev in https://github.com/probabl-ai/skore/pull/1956#discussion_r2245737102_
=> chore(skore)!: Rename `cv_splitter` to `splitter` in cross-validation

ci/requirements/skore/python-3.10/scikit-learn-1.4/test-requirements.txt, ci/requirements/skore/python-3.10/scikit-learn-1.7/test-requirements.txt, ci/requirements/skore/python-3.11/scikit-learn-1.4/test-requirements.txt, ci/requirements/skore/python-3.11/scikit-learn-1.7/test-requirements.txt, ci/requirements/skore/python-3.12/scikit-learn-1.4/test-requirements.txt, ci/requirements/skore/python-3.12/scikit-learn-1.7/test-requirements.txt, ci/requirements/skore/python-3.13/scikit-learn-1.5/test-requirements.txt, ci/requirements/skore/python-3.13/scikit-learn-1.6/test-requirements.txt, ci/requirements/skore/python-3.13/scikit-learn-1.7/test-requirements.txt, skore/tests/unit/sklearn/plot/table_report/test_estimator.py
With current assertions, we are actually testing the `summarize_dataframe` function of skrub (cf [code](https://github.com/skrub-data/skrub/blob/693bff1afb3b87832c242f858be605cfbc87c47b/skrub/_reporting/_summarize.py#L12)), which changes over versions.  
For instance, they added with_associations parameter to the function, and the same key to the output: therefore these tests are ok with skrub 0.5.4, but fail with 0.6.0, while it doesn't affect skore.  
Fixes #1954
=> chore: Correct test to be compliant with several skrub versions

examples/model_evaluation/plot_train_test_split.py
=> docs: Update the train-test split example to use as_dict parameter 

.github/workflows/pytest.yml
Counter-intuitively, tests take longer to run in parallel.
=> ci: Run tests serially

skore-local-project/src/skore_local_project/project.py, skore-local-project/tests/unit/test_project.py
The attribute `_cache` can't be missing after depickling the report:
```python
File skore/_sklearn/_estimator/metrics_accessor.py:1461, in _MetricsAccessor._rmse(self, data_source, data_source_hash, X, y, multioutput)
1439 @available_if(
1440     _check_supported_ml_task(
1441         supported_ml_tasks=["regression", "multioutput-regression"]
(...)   1453     ) = "raw_values",
1454 ) -> float | list:
1455     """Private interface of `rmse` to be able to pass `data_source_hash`.
1456 
1457     `data_source_hash` is either an `int` when we already computed the hash
1458     and are able to pass it around or `None` and thus trigger its computation
1459     in the underlying process.
1460     """
-> 1461     result = self._compute_metric_scores(
1462         metrics.root_mean_squared_error, …
```
=> fix(skore-local-project): Clear the report cache instead of deleting it before serialization

skore-local-project/src/skore_local_project/metadata.py, skore-local-project/src/skore_local_project/project.py, skore-local-project/tests/conftest.py, skore-local-project/tests/unit/test_project.py
Part of https://github.com/probabl-ai/skore/issues/1923.
=> feat(skore-local-project): Add `CrossValidationReport` metadata to `summarize`
