.gitattributes

docs: Promote repository primary language to python

---

src/skore/cli/launch_dashboard.py
src/skore/ui/app.py

refactor(launch): Replace thread with lifespan event for opening the browser

---

pyproject.toml

guideline: https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#about-your-project

docs: Enhance description of project on PyPI (#395)

---

README.md
skore/pyproject.toml

fix(readme): Fix badges

---

.github/workflows/lint.yml
.pre-commit-config.yaml
examples/skrub_demo.ipynb

chore(pre-commit): Ensure the notebooks are cleaned

---

.github/workflows/release.yml

chore(ci): Post release announce to slack

---

examples/01_basic_usage.ipynb
examples/01_basic_usage.py

docs(plotly): Add warning about plotly/nbformat issue

---

README.md

Fixing https://github.com/probabl-ai/skore/issues/529

docs(discord): Add Discord badge in README

---

examples/00_getting_started.ipynb
examples/00_getting_started.py
examples/01_basic_usage.ipynb
examples/01_basic_usage.py
skore/tests/unit/test_project.py

- **Add test for behaviour of `load` of a project without `.skore`**
- **docs: Update docs to remove `.skore` from project name where it is ambiguous**
Closes #547

docs: Remove `.skore` from project name in docs where it is ambiguous

---

skore-ui/src/assets/styles/_variables.css
skore-ui/src/components/DataFrameWidget.vue
skore-ui/src/components/DropdownButton.vue
skore-ui/src/components/EditableListItem.vue
skore-ui/src/components/ModalDialog.vue
skore-ui/src/components/TextInput.vue
skore-ui/src/components/TreeAccordion.vue
skore-ui/src/components/TreeAccordionItem.vue
skore-ui/src/views/ComponentsView.vue
skore-ui/src/views/project/ProjectItemList.vue
skore-ui/src/views/project/ProjectView.vue
skore-ui/src/views/project/ProjectViewList.vue

Also shadow colors should now be correct and number of variables as been reduced.

feat(UI): Use corrects background colors, use orange for views and blue for items

---

skore-ui/src/components/TreeAccordion.vue

This fixes a problem introduced in https://github.com/probabl-ai/skore/commit/2393378debfc3903cca300e954288a201c2d5900#diff-a53f31132b666510175172f97266d64794afa1a64ad7e2b89b59642b858d7ad7R55
Closes #587

fix(ui): Correct wrong background color in TreeAccordion

---

sphinx/conf.py

docs(example-gallery): Sort example gallery by file name

---

skore/src/skore/cross_validate.py

Co-authored-by: Thomas S <thomas@probabl.ai>

fix: Calling `cross_validate` outside of a notebook doesn't log to the console anymore

---

skore-ui/src/models.ts
skore-ui/src/stores/project.ts
skore-ui/tests/stores/project.spec.ts
skore/src/skore/ui/project_routes.py
skore/tests/integration/ui/test_ui.py

feat: Export to front-end all versions of an item, but only use the latest version in the front-end

---

sphinx/conf.py

fix(docs): Add references in `conf.py`

---

README.md
examples/plot_01_getting_started.py
examples/plot_02_overview_skore_ui.py
examples/plot_03_cross_validate.py
skore/src/skore/cross_validate.py
skore/src/skore/project.py

Should close https://github.com/probabl-ai/skore/issues/670

docs: Fix backticks for rST

---

skore/pyproject.toml

Fixes https://github.com/probabl-ai/skore/issues/559
The badge in the Readme should be fixed once this commit is released on PyPI.

fix(license): Fix license tag in pyproject.toml

---

sphinx/index.rst

Closes https://github.com/probabl-ai/skore/issues/687

docs: Fix declared license

---

skore/src/skore/item/item_repository.py

Small refactor by @augustebaum to please mypy.

feat(UI): Add typings to `item_repository`

---

examples/plot_03_cross_validate.py

Closes https://github.com/probabl-ai/skore/issues/700

fix(docs): Minor change in cross-validation example

---

README.md

fix(docs): Add downloads badge in the README

---

examples/plot_02_overview_skore_project.py

fix(docs): Rename example file

---

skore/src/skore/project/project.py

The method is a helper that should not be exposed.
Addresses #735

refactor!: Make `Project.put_one` private

---

skore/src/skore/sklearn/cross_validate.py

docs(cross-validate): Describe what `cross_validate` does in docstring

---

skore/src/skore/sklearn/train_test_split/warning/__init__.py
skore/src/skore/sklearn/train_test_split/warning/stratify_is_set.py
skore/tests/unit/sklearn/train_test_split/test_train_test_split.py
skore/tests/unit/sklearn/train_test_split/warning/test_stratify_warning.py

feat(train_test_split): Add "stratify" warning

---

examples/plot_02_overview_skore_project.py
skore/pyproject.toml

fix(docs): Update skore project example

---

examples/plot_04_tracking_items.py

fix(docs): Improve the tracking example

---

skore-ui/src/components/ImageWidget.vue
skore-ui/src/stores/project.ts
skore-ui/src/views/project/ProjectView.vue
skore/src/skore/ui/project_routes.py

fix: Item media type now includes base64 encoding

---

skore-ui/src/components/TreeAccordionItem.vue

When hovering an already added item.

feat(UI): Uses pointer instead of help 

---

README.md
examples/00_getting_started/plot_01_getting_started.py

fix(docs): Update the getting started example v0.4

---

skore/src/skore/project/project.py

docs(Project): Detail the relationship between `put` and `get`

---

skore/src/skore/sklearn/cross_validation/cross_validation_reporter.py
skore/src/skore/sklearn/cross_validation/plot.py
skore/tests/integration/sklearn/test_cross_validate.py

Closes https://github.com/probabl-ai/skore/issues/858

feat(cross-validation): Add `fit_time_per_data_point` and `score_time_per_data_point` metrics

---

README.md

fix(docs): Update the logo in the README

---

README.md
sphinx/_static/images/Probabl-logo-blue.png
sphinx/_static/images/Probabl-logo-orange.png

fix(docs): Host Probabl logo

---

README.md
examples/00_getting_started/plot_01_getting_started.py
examples/01_track/plot_02_tracking_items.py
examples/02_diagnose/plot_01_cross_validate.py
examples/02_diagnose/plot_02_train_test_split.py
sphinx/_static/images/2024_12_09_skore_activity_feed.png
sphinx/index.rst

fix(docs): Update examples before release v0.5

---

examples/00_getting_started/plot_01_getting_started.py
examples/01_track/plot_02_tracking_items.py
sphinx/_static/images/2024_11_21_tracking_comp.gif
sphinx/_static/images/2024_12_10_tracking_comp.gif

fix(docs): Update the tracking GIF before release v0.5

---

examples/00_getting_started/plot_01_getting_started.py
examples/01_track/plot_02_tracking_items.py
sphinx/index.rst

Fix #913 
- index page
- quick start beginning

fix(docs): Update the index page of the doc before release 0.5

---

sphinx/conf.py

fix(docs): Add some intershphinx in `conf.py`

---

skore/src/skore/project/create.py
skore/src/skore/sklearn/cross_validation/cross_validation_reporter.py

- Update docstring of `skore.CrossValidationReporter`
- Update docstring of `skore.create`

docs: Update docstrings

---

README.md
examples/00_getting_started/plot_01_getting_started.py
sphinx/_static/images/2024_12_12_skore_demo_comp.gif
sphinx/getting_started.rst
sphinx/index.rst

fix(docs): Update the GIFs following cross-validation reporter, before release 0.5

---

README.md
sphinx/install.rst

docs: Document how to install from conda-forge

---

examples/01_track/plot_02_tracking_items.py
examples/02_diagnose/plot_01_cross_validate.py

fix(docs): Remove examples about cross-validation aggregation for now

---

skore/pyproject.toml
sphinx/conf.py
sphinx/install.rst

docs: Add tabs in installation guide to choose installation method

---

skore-ui/src/router.ts

feat(UI): Activity feed is now the default route

---

README.md
sphinx/_static/images/2024_11_21_cross_val_comp.gif
sphinx/_static/images/2024_12_05_skore_demo_comp.gif
sphinx/_static/images/2024_12_12_skore_cross_val.png
sphinx/_static/images/2024_12_12_skore_demo_comp.gif

docs: Update GIF to make it shorter

---

README.md
examples/00_getting_started/plot_01_getting_started.py
examples/01_track/plot_02_tracking_items.py
sphinx/_static/images/2024_12_12_skore_cross_val_clf.png

docs: Minor change for the screenshot in the README

---

sphinx/index.rst

docs: Update the index page (minor)

---

skore/src/skore/ui/project_routes.py

This way the function is defined only once.

refactor: Move nested function to a higher scope

---

skore/tests/unit/item/test_cross_validation_item.py

As requested in https://github.com/probabl-ai/skore/pull/871#discussion_r1880504995

test(CrossValidationItem): Test that `cv_info` is present

---

CONTRIBUTING.rst
README.md
examples/README.txt
examples/getting_started/README.txt
examples/getting_started/plot_quick_start.py
examples/getting_started/plot_skore_product_tour.py
examples/getting_started/plot_tracking_items.py
examples/getting_started/plot_working_with_projects.py
examples/model_evaluation/README.txt
examples/model_evaluation/plot_cross_validate.py
examples/model_evaluation/plot_train_test_split.py
examples/track/README.txt
sphinx/_static/css/custom.css
sphinx/conf.py
sphinx/index.rst
sphinx/install.rst

docs: Modify the doc following the v0.5 release, part 1

---

docs/design/0002-never-present-neg-metrics-from-sklearn.md

docs: Add ADR on `neg_*` metrics

---

README.md

The readme was not updated with the new open function.

chore: Fix readme

---

README.md

By default, `create=True` in `open` so no need to specify it

docs: Minor change in the README.md

---

skore/src/skore/sklearn/_estimator/metrics_accessor.py
skore/src/skore/sklearn/_estimator/report.py
skore/src/skore/sklearn/_plot/utils.py

Instead of using the direct emoji, let's change it to the markup one.
However, it does not fix the issue in width in ipython.

chore: Use emoji markup as proposed in rich

---

.github/workflows/backend.yml
skore/pyproject.toml

Closes #1129
Co-authored-by: Guillaume Lemaitre <guillaume@probabl.ai>

ci: Avoid deadlock when computing coverage

---

skore-ui/src/components/ProjectViewCard.vue

fix(UI): Item card actions are now aligned

---

skore-ui/src/components/TreeAccordionItem.vue

fix(UI): Ellipsis long item name

---

skore-ui/src/components/CrossValidationReportResults.vue

feat(UI): New rules to format numbers in cv report

---

.github/workflows/backend.yml
examples/getting_started/plot_quick_start.py
skore/src/skore/project/open.py

docs: Refine the docstring of `open`

---

skore-ui/src/stores/project.ts
skore-ui/src/views/project/ItemNote.vue

And save a trimmed version of the text.
As requested in feedbacks.

feat(UI): Blur markdown editor when user clicks outside 

---

sphinx/index.rst

docs: Update the landing page of the docs

---

examples/model_evaluation/plot_estimator_report.py
skore/src/skore/sklearn/_base.py
skore/src/skore/sklearn/_cross_validation/metrics_accessor.py
skore/src/skore/sklearn/_cross_validation/report.py
skore/src/skore/sklearn/_estimator/metrics_accessor.py
skore/src/skore/sklearn/_estimator/report.py
skore/src/skore/sklearn/_plot/precision_recall_curve.py
skore/src/skore/sklearn/_plot/prediction_error.py
skore/src/skore/sklearn/_plot/roc_curve.py
skore/tests/unit/sklearn/test_base.py
skore/tests/unit/sklearn/test_cross_validation.py
skore/tests/unit/sklearn/test_estimator.py
sphinx/api.rst

docs: Ensure EstimatorReport and CrossValidationReport instances are called "report"

---

README.md
examples/getting_started/plot_quick_start.py
examples/getting_started/plot_skore_product_tour.py
examples/getting_started/plot_tracking_items.py
examples/getting_started/plot_working_with_projects.py
examples/model_evaluation/plot_cross_validate.py
sphinx/index.rst

docs: Hide mentions of the skore UI

---

sphinx/_static/css/custom.css

Closes https://github.com/probabl-ai/skore/issues/1183
Before:
After:

docs: Make left sidebar thinner

---

examples/getting_started/plot_skore_getting_started.py
examples/model_evaluation/plot_estimator_report.py
examples/technical_details/plot_cache_mechanism.py
examples/use_cases/plot_employee_salaries.py

docs: Refine the documentation before the release 0.6.1

---

examples/getting_started/plot_skore_getting_started.py
examples/model_evaluation/plot_train_test_split.py
examples/technical_details/README.txt
examples/technical_details/plot_cache_mechanism.py
examples/use_cases/README.txt
examples/use_cases/plot_employee_salaries.py

Fix some minor typos, make some parts clearer, add some sections, etc

docs: Refine example `plot_cache_mechanism`

---

examples/getting_started/plot_quick_start.py
examples/getting_started/plot_skore_getting_started.py
examples/getting_started/plot_tracking_items.py
examples/getting_started/plot_working_with_projects.py
examples/model_evaluation/plot_cross_validate.py
examples/model_evaluation/plot_estimator_report.py
examples/model_evaluation/plot_train_test_split.py
examples/technical_details/plot_cache_mechanism.py
examples/use_cases/plot_employee_salaries.py
skore-ui/src/stores/project.ts

docs: Minor changes of the doc examples for v0.6

---

sphinx/conf.py

requested in https://github.com/probabl-ai/skore/issues/1008

docs: Remove skore logo as default thumbnail

---

examples/getting_started/plot_quick_start.py
examples/model_evaluation/plot_train_test_split.py

Fix #1221 
and also minor change in the quick start guide

docs: No need to create a skore project in some examples

---

skore/src/skore/sklearn/find_ml_task.py
skore/src/skore/sklearn/types.py
skore/tests/unit/sklearn/test_utils.py
skore/tests/unit/utils/test_accessors.py

refactor: Change unsupported to unknown

---

README.md
sphinx/api.rst

docs: Minor changes

---

skore/src/skore/sklearn/find_ml_task.py
skore/tests/unit/sklearn/test_utils.py

Closes #1324
closes https://github.com/probabl-ai/skore/issues/1357

fix(_find_ml_task): Make `_find_ml_task` work for non-numpy arrays

---

examples/use_cases/plot_employee_salaries.py

fix(docs): Change axis of concat

---

skore/src/skore/project/project.py

docs(project): Make it clearer that a project can be initialized

---

.github/workflows/release.yml

This PR should fix https://github.com/probabl-ai/skore/issues/1344 issue

ci: Fix SlackAPI call

---

examples/use_cases/plot_employee_salaries.py

docs: Fix plot_employee_salaries.py example

---

README.md
sphinx/conf.py

docs: Add link to YouTube playlist

---

examples/use_cases/plot_feature_importance.py

docs: Reverse order in plot

---

skore/ci/requirements/python-3.10/scikit-learn-1.6/test-requirements.txt
skore/ci/requirements/python-3.11/scikit-learn-1.6/test-requirements.txt
skore/ci/requirements/python-3.12/scikit-learn-1.4/test-requirements.txt
skore/ci/requirements/python-3.12/scikit-learn-1.5/test-requirements.txt
skore/ci/requirements/python-3.12/scikit-learn-1.6/test-requirements.txt
skore/ci/requirements/python-3.9/scikit-learn-1.6/test-requirements.txt

fix vulnerability alert. No actual risk, but just to avoid getting the warnings.

chore: Update jinja2

---

examples/getting_started/plot_skore_getting_started.py

Changes:
- real-world data
- using rf and gb models
- more about the tracking functionalities

docs: Refine the getting started guide

---

examples/getting_started/plot_quick_start.py
examples/getting_started/plot_skore_getting_started.py

docs: Some refinement of `plot_skore_getting_started.py`

---

skore/src/skore/project/project.py

Add `default` to the parameters list for some functions

docs(project): Revise docstrings

---

skore/tests/unit/persistence/test_disk.py

Closes https://github.com/probabl-ai/skore/issues/1468.

fix: Remove symlink in unittests to be runnable on non-privileged Windows

---

skore/src/skore/sklearn/_comparison/metrics_accessor.py
skore/src/skore/sklearn/_cross_validation/metrics_accessor.py
skore/src/skore/sklearn/_estimator/metrics_accessor.py
skore/tests/unit/sklearn/comparison/test_comparison.py
skore/tests/unit/sklearn/test_cross_validation.py
sphinx/reference/report/comparison_report.rst
sphinx/reference/report/cross_validation_report.rst

closes #1479 
Add `timings` method to `CrossValidationReport` and `ComparisonReport`.

feat: Implement timings for CrossValidationReport and ComparisonReport

---

CONTRIBUTING.rst

Following some feedback from contributors.

docs: Extend contributing guide

---

examples/use_cases/plot_feature_importance.py

Closes https://github.com/probabl-ai/skore/issues/1521

docs: Refer to `feature_importance.coefficients` rather than `feature_importance` itself

---

skore-remote-project/src/skore_remote_project/project/metadata.py
skore-remote-project/src/skore_remote_project/project/widget.py

This should fix a couple of bugs observe in https://github.com/probabl-ai/skore/pull/1475
The demo I tried is:
```python
from skore.project import open
if "project" not in globals():
project = open("remote", name="robin", tenant="Probabl")
metadata = project.metadata()
metadata
reports = metadata.reports()
from skore import ComparisonReport
report = ComparisonReport(reports)
report.metrics.report_metrics()
```

fix: Fixes search and parallel coordinate widget

---

sphinx/index.rst

docs: Add Plausible tracker

---

examples/getting_started/plot_skore_getting_started.py

docs: Add some `indicator_favorability=True` in the getting started guide

---

examples/use_cases/plot_employee_salaries.py

Following https://github.com/probabl-ai/skore/pull/1512
With the help of @auguste-probabl:
Co-authored-by: auguste-probabl <auguste@probabl.ai>

docs: Include the comparison of cross-validation reports in the examples

---

skore-remote-project/src/skore_remote_project/item/skore_estimator_report_item.py
skore-remote-project/tests/unit/item/test_skore_estimator_report_item.py

Closed https://github.com/probabl-ai/skore/issues/1630.

feat(skore-remote-project): Add `verbose_name` to metric DTO

---

examples/model_evaluation/plot_estimator_report.py
skore/src/skore/sklearn/_plot/metrics/confusion_matrix.py

resolves https://github.com/probabl-ai/skore/issues/1639

fix(confusion matrix): Set default colormap to 'Blues' for readability

---

skore-remote-project/src/skore_remote_project/client/api.py
skore-remote-project/src/skore_remote_project/client/client.py
skore-remote-project/src/skore_remote_project/item/skore_estimator_report_item.py
skore-remote-project/src/skore_remote_project/project/project.py
skore-remote-project/tests/unit/project/test_project.py

Some minor improvements to prepare for the arrival of the new `search` feature:
-  Add `follow_redirects` instruction in each HTTPX call,
-  Add experiments accessor.

feat(skore-estimator-report): Add experiments accessor

---

.github/workflows/pr-commits-verification.yml

Closes https://github.com/probabl-ai/skore/issues/1657.

ci: Add `pr-commits-verification.yml` to comment PR on unsigned commits

---

skore-remote-project/src/skore_remote_project/project/project.py
skore-remote-project/tests/unit/project/test_project.py

Allow to put only `skore.EstimatorReport`, as long as we can't get them back or display them in the hub.

feat(skore-remote-project): Allow to put only `skore.EstimatorReport`

---

skore/src/skore/sklearn/_plot/metrics/precision_recall_curve.py
skore/src/skore/sklearn/_plot/metrics/prediction_error.py
skore/src/skore/sklearn/_plot/metrics/roc_curve.py

refactor(plots): Make internal plot methods non-static

---

CONTRIBUTING.rst

Fix #1653 
this PR closes PR https://github.com/probabl-ai/skore/pull/1653 as @AchrafTasfaout did not sign his commits
Co-authored-by: AchrafTasfaout <achraf.tasfaout@gmail.com>

docs: Add instruction to check the dev version of doc

---

.github/workflows/release.yml

Following https://github.com/probabl-ai/skore/pull/1680.

ci: Improve `release.yml` docstr

---

examples/skore_project/plot_tracking_items.py

docs: Fix typo

---

skore/src/skore/sklearn/_estimator/metrics_accessor.py
skore/tests/unit/sklearn/estimator/test_estimator.py

Closes #1519 .
---
Hi @auguste-probabl , @MarieSacksick !
I've resolved the issue [#1519](https://github.com/probabl-ai/skore/issues/1519) in  the `report_metric` function to scores the report metrics string. Could you please review the PR .
Thank You !

feat: Make it possible to pass any scikit-learn metric string to `report_metrics`

---

skore/src/skore/project/project.py
skore/src/skore/project/widget.py
skore/tests/unit/project/test_widget.py

Adding test for the `ModelExplorerWidget` class.

test: Test the parallel coordinate widget

---

sphinx/_static/images/screenshot_getting_started.png
sphinx/_static/images/screenshot_quick_start.png

For https://github.com/probabl-ai/skore/pull/1717, I need the following screenshots.

docs: Add screenshots of parallel coordinates plots

---

skore/tests/unit/project/test_widget.py

Fixes the failure in `test_widget.py` by assigning a sequence of the same size.

fix: Assign the proper length sequence

---

skore/src/skore/project/metadata.py
skore/tests/unit/project/test_metadata.py

Fix a bug when multiple selections are done on other axis than learners

fix: Add more tests for multiple selection on the parallel coordinate plot

---

README.md
sphinx/index.rst

Co-authored-by: tuscland <cam@probabl.ai>

docs: Update README.md

---

skore/src/skore/project/metadata.py
skore/tests/unit/project/test_metadata.py

I don't think that we need this method to be exposed to the user for the moment.
We can always make it public if we get a feature request.

chore: Make _query_string_selection private

---

skore/pyproject.toml
skore/src/skore/project/metadata.py
skore/src/skore/project/project.py
skore/tests/unit/project/test_metadata.py
skore/tests/unit/project/test_project.py

Improve `skore/project/` coverage by:
- adding tests,
- always disabling coverage on `if TYPE_CHECKING:` precondition,
- specifically disabling coverage in `project.py` on `if sys.version_info < (3, 10)` precondition.

feat(skore): Improve `skore/project/` coverage

---

.github/workflows/pr-display-code-coverage.yml
.github/workflows/pytest.yml

Following https://github.com/probabl-ai/skore/pull/1666 and https://github.com/probabl-ai/skore/pull/1766.

ci: Fix `pr-display-code-coverage` after #1766

---

skore/src/skore/sklearn/_comparison/utils.py

Most probably some merge conflict remaining code.
No big deal.

chore: Small clean-up unecessary code

---

skore-hub-project/pyproject.toml
skore-hub-project/src/skore_hub_project/authentication/logout.py
skore-hub-project/tests/unit/authentication/test_logout.py

Closes https://github.com/probabl-ai/skore/issues/1798.

feat(skore-hub-project): Add `skore-hub-logout` entry-point to remove cached token

---

skore/src/skore/project/widget.py
skore/tests/unit/project/test_widget.py

Fix grammar in the error message in the parallel coordinate plot.

fix(skore): Fix typos in console message printed by // plot widget

---

CONTRIBUTING.rst

Follow-up of https://github.com/probabl-ai/skore/pull/1831

docs: Update CONTRIBUTING.rst to reflect the new versions of Python

---

skore/src/skore/sklearn/_comparison/metrics_accessor.py
skore/src/skore/sklearn/_cross_validation/metrics_accessor.py
skore/src/skore/sklearn/_estimator/metrics_accessor.py

Closes https://github.com/probabl-ai/skore/issues/1624.

docs: Add docs to explain link between scorer and favorability

---

skore/src/skore/sklearn/_comparison/report.py
sphinx/user_guide/reporters.rst

Closes https://github.com/probabl-ai/skore/issues/1507.  
One of the task of the issue is "show what happens otherwise" (ie when y_target is not the same), but I don't think anymore that it's super relevant.

docs: Give more information about comparison report

---

skore/pyproject.toml

Closes https://github.com/probabl-ai/skore/issues/1893, and following TOML [guideline](https://toml.io/en/).

feat(skore): Improve PyPI description

---

examples/getting_started/plot_quick_start.py
examples/getting_started/plot_skore_getting_started.py
examples/model_evaluation/plot_estimator_report.py
examples/technical_details/plot_cache_mechanism.py
examples/use_cases/plot_employee_salaries.py
examples/use_cases/plot_feature_importance.py

Closes https://github.com/probabl-ai/skore/issues/1847

docs: Show dataframe instead of display objects in examples

---

examples/use_cases/plot_employee_salaries.py

docs: Minor update of plot_employee_salaries.py

---

examples/technical_details/plot_sklearn_api.py
skore/pyproject.toml
sphinx/conf.py

Fix https://github.com/probabl-ai/skore/issues/1451
Supersedes https://github.com/probabl-ai/skore/pull/1814 that is too long but archived for safe-keeping

docs: Add a technical example showing scikit-learn API compatible estimators that work with skore

---

skore/tests/unit/sklearn/plot/table_report/test_estimator.py

Remove useeless trailing fixture.

chore(test): Remove useless fixture

---

skore-hub-project/src/skore_hub_project/client/api.py
skore-hub-project/src/skore_hub_project/client/client.py
skore-hub-project/src/skore_hub_project/project/artefact.py
skore-hub-project/src/skore_hub_project/project/project.py
skore-hub-project/tests/unit/authentication/test_login.py
skore-hub-project/tests/unit/authentication/test_token.py
skore-hub-project/tests/unit/client/test_api.py
skore-hub-project/tests/unit/client/test_client.py
skore-hub-project/tests/unit/project/test_artefact.py
skore-hub-project/tests/unit/project/test_project.py

> Maybe you could implement a retry strategy here ?
> If connexion goes down for some reason you may want to retry the upload.
> 
> I reccoment to implement this using an exponential backoff algorithm.
_Originally posted by @rouk1 in https://github.com/probabl-ai/skore/pull/1911#discussion_r2224599273_
---
Mainly based on [urllib3.util.Retry](https://urllib3.readthedocs.io/en/stable/reference/urllib3.util.html#urllib3.util.Retry) and inspired by [httpx-retries](https://github.com/will-ockmore/httpx-retries).

feat(skore-hub-project): Add a retry strategy to client based on exponential backoff algorithm

---

skore/src/skore/_config.py
skore/src/skore/_sklearn/_plot/base.py
skore/src/skore/_sklearn/_plot/data/table_report.py
skore/src/skore/_sklearn/_plot/metrics/confusion_matrix.py
skore/src/skore/_sklearn/_plot/metrics/precision_recall_curve.py
skore/src/skore/_sklearn/_plot/metrics/prediction_error.py
skore/src/skore/_sklearn/_plot/metrics/roc_curve.py
skore/src/skore/_sklearn/_plot/utils.py
skore/src/skore/_sklearn/types.py
skore/tests/unit/test_config.py

feat(skore): Add infrastructure to support different plotting backends for Displays

---

examples/use_cases/plot_feature_importance.py

closes #1421 
Created a separated dataframe for features importances and rename the features by string replace operations. 
Changes were made for two figures:  `engineered_ridge_report`

docs(skore): Change the name of features after preprocessing

---

skore/src/skore/_sklearn/_cross_validation/report.py
skore/tests/unit/reports/cross_validation/test_report.py

Fix behavior for clustering in CrossValidationReport, and add according test

fix(skore): Fix behavior for clustering in `CrossValidationReport`

---

skore/src/skore/_sklearn/_plot/metrics/precision_recall_curve.py
skore/src/skore/_sklearn/_plot/metrics/prediction_error.py
skore/src/skore/_sklearn/_plot/metrics/roc_curve.py

Closes #1854 .
Clearly not urgent, just to remove issues from backlog.

chore: Adapt quotes

---

skore/pyproject.toml
skore/src/skore/project/project.py
skore/src/skore/project/summary.py
skore/tests/unit/project/test_project.py
skore/tests/unit/project/test_summary.py

Closes https://github.com/probabl-ai/skore/issues/1944 and https://github.com/probabl-ai/skore/issues/1923.

feat(skore/project)!: Put/get/summarize `CrossValidationReport`

---

skore/src/skore/_sklearn/_cross_validation/data_accessor.py
skore/src/skore/_sklearn/_estimator/data_accessor.py
sphinx/reference/report/estimator_report.rst

closes https://github.com/probabl-ai/skore/issues/1930

docs: Add data accessor to EstimatorReport documentation
